// Shared helpers for the Sumo Logic Tokens config type
// (deploy + rollback + drift + validate).
//
// A "token" here is a Collector Registration Token — a shared secret Collectors
// can present to auto-register with the organization without an individual
// user credential. The `type` is always `CollectorRegistration` on write (the
// only value the API accepts); NAME is the stable identity used to upsert.
// Update is optimistic-concurrency versioned (`version` must match the
// CURRENT live value or the request is rejected) — same shape as Monitors in
// this app. The actual token SECRET VALUE (`encodedTokenAndUrl`, embedded in
// the installer command a Collector runs) is generated by Sumo Logic and never
// re-exposed after creation — this config type manages the token's NAME,
// DESCRIPTION and Active/Inactive STATUS only, never the secret itself.
//   API: https://help.sumologic.com/docs/api/tokens-library-token-management/
//   Verified against the official Sumo Logic OpenAPI spec
//   (TokenBaseDefinition / TokenBaseDefinitionUpdate / TokenBaseResponse,
//   api.sumologic.com/docs/sumologic-api.yaml).

/** One Sumo Logic Collector Registration Token. */
export interface Token {
  id?: string
  name: string
  description?: string
  status: string
  type?: string
  version?: number
  [key: string]: unknown
}

/** The { data: [...] } envelope returned by GET /tokens (not paginated — returns every token). */
export interface TokenList {
  data?: Token[]
}

function s(value: unknown): string {
  return String(value ?? '').trim()
}

/** Unwrap the { data: [...] } list envelope into a flat array of tokens. */
export function tokensFromList(list: unknown): Token[] {
  if (Array.isArray(list)) return list as Token[]
  const data = (list as TokenList | null | undefined)?.data
  return Array.isArray(data) ? data : []
}

/** Find a live token by name (case-insensitive, trimmed) — the identity. */
export function findToken(tokens: Token[], name: string): Token | null {
  const n = name.trim().toLowerCase()
  if (!n) return null
  return tokens.find((t) => s(t.name).toLowerCase() === n) ?? null
}

/** Build the create-request body. */
export function buildTokenCreateBody(fields: Record<string, unknown>): Record<string, unknown> {
  return {
    type: 'CollectorRegistration',
    name: s(fields.name),
    description: s(fields.description),
    status: s(fields.status) || 'Active',
  }
}

/** Build the update-request body — requires the CURRENT live `version`. */
export function buildTokenUpdateBody(fields: Record<string, unknown>, currentVersion: number): Record<string, unknown> {
  return { ...buildTokenCreateBody(fields), version: currentVersion }
}
