import { test } from 'node:test'
import assert from 'node:assert/strict'
import validate from '../validate'
import { parseValueLines, settingsFromValues, findSetting } from '../_shared'
import type { PipelineContext } from '@veltrixsecops/app-sdk'

/**
 * deploy/rollback/drift apply over the SonarQube Web API via node:http(s) inside
 * sonarqubeApi, which is impractical to mock here. Tests focus on validate.ts and
 * _shared, which are pure and network-free.
 */
function toItems(list: Array<Record<string, unknown>>) {
  return list.map((fields, i) => ({ id: `i${i}`, name: String(fields.key ?? i), fields }))
}

function ctxOf(list: Array<Record<string, unknown>>): PipelineContext {
  return { canvas: { items: toItems(list) } } as unknown as PipelineContext
}

const singleValue = { key: 'sonar.forceAuthentication', value: 'true', values: '' }
const multiValue = { key: 'sonar.autogenerated', value: '', values: 'val1\nval2\nval3' }

// --- validate ------------------------------------------------------------------

test('validate accepts a well-formed single-value setting', async () => {
  const res = await validate(ctxOf([singleValue]))
  assert.equal(res.valid, true)
  assert.equal(res.errors.length, 0)
})

test('validate accepts a well-formed multi-value setting', async () => {
  const res = await validate(ctxOf([multiValue]))
  assert.equal(res.valid, true)
  assert.equal(res.errors.length, 0)
})

test('validate rejects a missing key', async () => {
  const res = await validate(ctxOf([{ ...singleValue, key: '' }]))
  assert.equal(res.valid, false)
  assert.ok(res.errors.some((e) => e.code === 'EMPTY_KEY'))
})

test('validate rejects a setting with neither value nor values', async () => {
  const res = await validate(ctxOf([{ ...singleValue, value: '', values: '' }]))
  assert.equal(res.valid, false)
  assert.ok(res.errors.some((e) => e.code === 'EMPTY_VALUE'))
})

test('validate rejects a setting with both value and values', async () => {
  const res = await validate(ctxOf([{ ...singleValue, value: 'true', values: 'a\nb' }]))
  assert.equal(res.valid, false)
  assert.ok(res.errors.some((e) => e.code === 'AMBIGUOUS_VALUE'))
})

test('validate warns on a duplicate key', async () => {
  const res = await validate(ctxOf([singleValue, { ...singleValue, value: 'false' }]))
  assert.equal(res.valid, true)
  assert.ok(res.warnings.some((w) => w.code === 'DUPLICATE_KEY'))
})

test('validate errors when there are no items', async () => {
  const res = await validate(ctxOf([]))
  assert.equal(res.valid, false)
  assert.ok(res.errors.some((e) => e.code === 'EMPTY'))
})

// --- parseValueLines -------------------------------------------------------------

test('parseValueLines strips blanks and comments', () => {
  const values = parseValueLines('val1\n\n# a comment\nval2\n  val3  ')
  assert.deepEqual(values, ['val1', 'val2', 'val3'])
})

test('parseValueLines returns an empty array for blank input', () => {
  assert.deepEqual(parseValueLines(''), [])
  assert.deepEqual(parseValueLines(undefined), [])
})

// --- settingsFromValues / findSetting ---------------------------------------------

test('settingsFromValues unwraps the settings envelope', () => {
  const settings = settingsFromValues({
    settings: [{ key: 'sonar.test.jira', value: 'abc', inherited: true }],
    setSecuredSettings: ['email.smtp_port.secured'],
  })
  assert.equal(settings.length, 1)
  assert.equal(settingsFromValues({}).length, 0)
})

test('findSetting matches by exact key', () => {
  const settings = [
    { key: 'sonar.test.jira', value: 'abc', inherited: true },
    { key: 'sonar.autogenerated', values: ['val1', 'val2', 'val3'], inherited: false },
  ]
  assert.equal(findSetting(settings, 'sonar.autogenerated')?.values?.length, 3)
  assert.equal(findSetting(settings, 'missing'), null)
})
