import type { CanvasSnapshot, PipelineContext, ValidationResult } from '@veltrixsecops/app-sdk'
import { coerceBoolean } from '../../lib/falcon'

// --- Falcon Next-Gen SIEM Data Connection API constraints ---------------------
//
// A data connection is an ingest connector instance. It lives on the ngsiem
// collection (verified against FalconPy's _ngsiem endpoint table):
//   GET    /ngsiem/combined/connections/v1              (list full entities — filter/limit/offset/sort)
//   GET    /ngsiem/entities/connections/v1?ids=…        (read by id)
//   POST   /ngsiem/entities/connections/v1              (create)
//   PATCH  /ngsiem/entities/connections/v1?ids=…        (update — connector_type is create-only)
//   DELETE /ngsiem/entities/connections/v1?ids=…        (delete)
//   GET/PATCH /ngsiem/entities/connections/status/v1?ids=…   (read / set enable-disable status)
//   GET/POST  /ngsiem/entities/connections/token/v1?ids=…    (Falcon-generated ingest token — out of scope)
//   GET    /ngsiem/combined/connectors/v1               (connector catalog — READ-ONLY reference)
//
// The connector_type is a catalog id (from the read-only connectors catalog) and
// is immutable after creation. The upstream auth secret lives inside `config`; it
// is a SECRET — sent on create/update, NEVER logged, NEVER stored in
// rollbackData/artifacts, and NEVER compared in drift. Falcon's own ingest token
// (for push connectors) is generated by the token endpoint, not set here.
//
// ⚠ The exact `config` sub-shape (endpoint/repository/credential keys) and the
// status enum are not fully enumerated by the published SDK; endpoint, repository
// and status are applied and diffed best-effort and should be confirmed against a
// live tenant.

/** Status values applied for enabled/disabled (best-effort — see deploy.ts). */
export const STATUS_ENABLED = 'enabled'
export const STATUS_DISABLED = 'disabled'

// --- Spec extraction shared by deploy / rollback / healthCheck / drift ---------

export interface ConnectionSpec {
  sectionName: string
  name: string
  /** Connector catalog id (immutable after create). */
  connectorType: string
  /** Non-secret upstream source endpoint. */
  sourceEndpoint?: string
  /** ⚠ SECRET — upstream auth credential/token. Never logged, stored, or diffed. */
  credential: string
  /** Non-secret ingest target repository. */
  targetRepository: string
  /** Non-secret parser assignment. */
  parser?: string
  enabled: boolean
}

/**
 * Shape of a data connection returned by the ngsiem connections collection. Only
 * NON-SECRET fields are modeled; the credential inside `config` is never read
 * back. `config` may echo non-secret params (endpoint/repository) — the drift
 * check reads only those keys from it, never the credential.
 */
export interface LiveDataConnection {
  id?: string
  name?: string
  connector_id?: string
  connector_type?: string
  parser?: string
  status?: string
  state?: string
  description?: string
  repository?: string
  config?: Record<string, unknown>
  /** Last modifier recorded by Falcon — used for drift attribution (best-effort). */
  modified_by?: string
  modified_timestamp?: string
  modified_on?: string
}

/** Each canvas section describes one data connection. */
export function extractConnectionSpecs(canvas: CanvasSnapshot): ConnectionSpec[] {
  return (canvas.sections ?? []).map((section) => {
    const fields = section.fields ?? {}
    return {
      sectionName: section.name,
      name: typeof fields.name === 'string' ? fields.name.trim() : '',
      // Connector types are catalog ids (e.g. "aws-s3") — trimmed, case preserved.
      connectorType: typeof fields.connectorType === 'string' ? fields.connectorType.trim() : '',
      sourceEndpoint:
        typeof fields.sourceEndpoint === 'string' && fields.sourceEndpoint.trim()
          ? fields.sourceEndpoint.trim()
          : undefined,
      // The secret is kept verbatim and never surfaced except in the request body.
      credential: typeof fields.credential === 'string' ? fields.credential : '',
      targetRepository:
        typeof fields.targetRepository === 'string' ? fields.targetRepository.trim() : '',
      parser:
        typeof fields.parser === 'string' && fields.parser.trim() ? fields.parser.trim() : undefined,
      enabled: coerceBoolean(fields.enabled, true),
    }
  })
}

/** True when the spec carries a non-empty secret (whitespace-only counts as none). */
export function hasCredential(spec: ConnectionSpec): boolean {
  return spec.credential.trim().length > 0
}

/** Live repository, best-effort: top-level field or a non-secret `config.repository`. */
export function liveRepository(live: LiveDataConnection): string | undefined {
  if (typeof live.repository === 'string') return live.repository
  const fromConfig = live.config?.repository
  return typeof fromConfig === 'string' ? fromConfig : undefined
}

/** Live enable/disable status, best-effort (`status` then `state`). */
export function liveStatus(live: LiveDataConnection): string | undefined {
  if (typeof live.status === 'string') return live.status
  return typeof live.state === 'string' ? live.state : undefined
}

// --- Validate handler ---------------------------------------------------------

/**
 * Validate data connection configurations against the API constraints: name,
 * connectorType and targetRepository are required; names must be unique per
 * canvas. The secret is never validated for content and never echoed in a message.
 */
export default async function validate(ctx: PipelineContext): Promise<ValidationResult> {
  const errors: ValidationResult['errors'] = []
  const warnings: ValidationResult['warnings'] = []

  const sections = ctx.canvas.sections
  if (!sections || sections.length === 0) {
    errors.push({ field: 'sections', message: 'Canvas has no configuration sections', code: 'empty_canvas' })
    return { valid: false, errors, warnings }
  }

  const specs = extractConnectionSpecs(ctx.canvas)
  const seenNames = new Set<string>()

  for (const spec of specs) {
    const prefix = spec.sectionName

    // name — the logical identity a connection is reconciled by
    if (!spec.name) {
      errors.push({ field: `${prefix}.name`, message: 'Connection name is required', code: 'required' })
    } else {
      const key = spec.name.toLowerCase()
      if (seenNames.has(key)) {
        errors.push({
          field: `${prefix}.name`,
          message: `Duplicate connection "${spec.name}" — each connection may only be declared once per canvas`,
          code: 'duplicate_name',
        })
      }
      seenNames.add(key)
    }

    // connectorType — the catalog connector id (immutable after create)
    if (!spec.connectorType) {
      errors.push({
        field: `${prefix}.connectorType`,
        message: 'Connector type is required — pick a connector id from the Next-Gen SIEM connector catalog',
        code: 'required',
      })
    }

    // targetRepository — where the connection ingests
    if (!spec.targetRepository) {
      errors.push({
        field: `${prefix}.targetRepository`,
        message: 'Target repository is required',
        code: 'required',
      })
    }

    // credential — advisory: a new connection with no credential cannot authenticate upstream
    if (!hasCredential(spec)) {
      warnings.push({
        field: `${prefix}.credential`,
        message:
          'No credential supplied — a new connection will be created without upstream authentication and may fail to ingest',
        code: 'no_credential',
      })
    }
  }

  return { valid: errors.length === 0, errors, warnings }
}
