import type { DeployContext, DeployResult } from '@veltrixsecops/app-sdk'
import { buildSplunkUrl, buildAuthHeader, getEntityContent, getJson, postForm, splunkRequest } from '../../lib/splunkApi'

/**
 * Deploy HEC token configuration via the REST API. Tokens live in the
 * splunk_httpinput app, so management goes through the servicesNS path:
 *   create:  POST   /servicesNS/admin/splunk_httpinput/data/inputs/http           (name=<token>)
 *   update:  POST   /servicesNS/admin/splunk_httpinput/data/inputs/http/<token>
 *   enable:  POST   .../http/<token>/enable    disable: .../http/<token>/disable
 *
 * Canvas → Splunk REST parameter mapping:
 *   defaultIndex      → index       (default index for events)
 *   allowedIndexes    → indexes     (comma-separated allow-list)
 *   defaultSourcetype → sourcetype
 *   defaultSource     → source
 *   description       → description
 *   useACK            → useACK      (1/0 — indexer acknowledgment)
 *   enabled           → enable/disable sub-endpoints
 *
 * The token VALUE is generated by Splunk and intentionally NOT included in
 * artifacts or rollback data — operators read it from Splunk directly.
 */

export const HEC_BASE_PATH = '/servicesNS/admin/splunk_httpinput/data/inputs/http'

/** Token settings snapshotted for rollback. */
const ROLLBACK_KEYS = ['index', 'indexes', 'sourcetype', 'source', 'description', 'useACK', 'disabled'] as const

/** A field the View modal renders (with copy / secret-masking). */
interface ResourceField {
  label: string
  value: string
  /** Masked with a reveal toggle in the UI (e.g. the token value). */
  secret?: boolean
  /** Show a copy button. */
  copyable?: boolean
}
/** One deployed resource surfaced read-only in the config View modal. */
interface DeployedResource {
  name: string
  fields: ResourceField[]
}

export default async function deploy(ctx: DeployContext): Promise<DeployResult> {
  const { component, credential, connectivity, connectivityProvider, canvas } = ctx

  // A managed-ZTNA host has no direct `connectivity` record — it is reached over
  // the tailnet via `connectivityProvider` (deviceAddress). Accept either.
  if (!credential) {
    return { success: false, message: 'Missing credential for HEC token deployment' }
  }
  if (!connectivity && !connectivityProvider) {
    return { success: false, message: 'Missing connectivity for HEC token deployment' }
  }

  const baseUrl = buildSplunkUrl(component, connectivity, connectivityProvider)
  const auth = buildAuthHeader(credential)

  // Pre-flight: every index a token routes to must exist on the target, or
  // splunkd rejects the token with a 400 mid-loop (leaving a partial deploy).
  // Validate up front and fail with a precise, per-host message. Best-effort:
  // if the live index list can't be read, skip the check and let the token POST
  // surface the real error rather than blocking on a transient read failure.
  const referencedIndexes = collectReferencedIndexes(canvas.sections)
  if (referencedIndexes.length > 0) {
    const liveIndexes = await listIndexNames(baseUrl, auth)
    if (liveIndexes) {
      const missing = referencedIndexes.filter((idx) => !liveIndexes.has(idx))
      if (missing.length > 0) {
        const plural = missing.length > 1
        const available = [...liveIndexes].sort().join(', ') || '(none)'
        return {
          success: false,
          message:
            `Index ${missing.map((m) => `'${m}'`).join(', ')} ${plural ? 'do' : 'does'} not exist on ` +
            `${component.hostname} (available: ${available}). Pick a valid index for this server, ` +
            `or scope Target Server Types to a server that has ${plural ? 'them' : 'it'}.`,
        }
      }
    }
  }

  // Ensure the GLOBAL HEC input ("http") is enabled — a token receives nothing
  // while HTTP Event Collector is globally disabled, which search heads default
  // to (this is what the health check's `hec_enabled` check flags). Idempotent +
  // best-effort: it never fails the deploy, but the outcome is surfaced so the
  // operator knows if it couldn't be turned on.
  let hecGloballyEnabled = true
  try {
    await splunkRequest(`${baseUrl}${HEC_BASE_PATH}/http/enable`, { method: 'POST', headers: auth })
  } catch {
    hecGloballyEnabled = false
  }

  const rollbackSnapshot: Record<string, unknown>[] = []
  const createdTokens: string[] = []
  const deployedTokens: string[] = []
  const resources: DeployedResource[] = []

  try {
    for (const section of canvas.sections) {
      const fields = section.fields
      const tokenName = fields.name as string
      if (!tokenName) continue

      const tokenPath = `${HEC_BASE_PATH}/${encodeURIComponent(tokenName)}`

      // Capture current state for rollback (token value excluded — it never changes)
      const existing = await getEntityContent(baseUrl, auth, tokenPath)
      if (existing) {
        const snapshot: Record<string, unknown> = { name: tokenName }
        for (const key of ROLLBACK_KEYS) {
          if (existing[key] !== undefined) snapshot[key] = existing[key]
        }
        rollbackSnapshot.push(snapshot)
      }

      const payload = buildTokenPayload(fields)

      if (existing) {
        await postForm(baseUrl, auth, tokenPath, payload)
      } else {
        await postForm(baseUrl, auth, HEC_BASE_PATH, { name: tokenName, ...payload })
        createdTokens.push(tokenName)
      }

      // Enabled state is toggled through dedicated sub-endpoints
      if (typeof fields.enabled === 'boolean') {
        const action = fields.enabled ? 'enable' : 'disable'
        await splunkRequest(`${baseUrl}${tokenPath}/${action}`, { method: 'POST', headers: auth })
      }

      // Fetch the token's final state to capture the Splunk-generated token VALUE
      // + routing for the View modal (this is the value operators copy into their
      // event sources). Best-effort — a read failure just omits the details.
      const final = await getEntityContent(baseUrl, auth, tokenPath)
      if (final) resources.push(buildTokenResource(tokenName, component.hostname, final))

      deployedTokens.push(tokenName)
    }

    const hecWarning = hecGloballyEnabled
      ? ''
      : ` — WARNING: could not enable the global HTTP Event Collector input on ${component.hostname}; tokens will not receive events until HEC is enabled there`
    return {
      success: true,
      message: `Deployed ${deployedTokens.length} HEC token(s): ${deployedTokens.join(', ')}${hecWarning}`,
      artifacts: { deployedTokens, createdTokens, hecGloballyEnabled, resources },
      rollbackData: { previousState: rollbackSnapshot, createdTokens },
    }
  } catch (error) {
    return {
      success: false,
      message: `HEC token deployment failed after ${deployedTokens.length} token(s): ${error instanceof Error ? error.message : 'Unknown error'}`,
      artifacts: { deployedTokens, createdTokens, failedAt: canvas.sections[deployedTokens.length]?.fields?.name },
      rollbackData: { previousState: rollbackSnapshot, createdTokens },
    }
  }
}

/** Build the View-modal resource for a deployed token from its live splunkd content. */
function buildTokenResource(
  name: string,
  hostname: string,
  content: Record<string, unknown>,
): DeployedResource {
  const s = (v: unknown): string | undefined =>
    v === undefined || v === null || v === '' ? undefined : String(v)
  const bool = (v: unknown): boolean => v === true || v === '1' || v === 1
  return {
    name: `${name} · ${hostname}`,
    fields: [
      { label: 'Token', value: s(content.token) ?? '(unavailable)', secret: true, copyable: true },
      { label: 'Name', value: name, copyable: true },
      { label: 'Server', value: hostname },
      { label: 'Enabled', value: bool(content.disabled) ? 'No' : 'Yes' },
      { label: 'Default Index', value: s(content.index) ?? '—' },
      { label: 'Allowed Indexes', value: s(content.indexes) ?? 'any' },
      { label: 'Sourcetype', value: s(content.sourcetype) ?? '—' },
      { label: 'Source', value: s(content.source) ?? '—' },
      { label: 'Indexer Acknowledgment', value: bool(content.useACK) ? 'Yes' : 'No' },
    ],
  }
}

/** Map canvas fields to Splunk REST parameters. */
function buildTokenPayload(fields: Record<string, unknown>): Record<string, string | undefined> {
  const allowedIndexes = Array.isArray(fields.allowedIndexes)
    ? (fields.allowedIndexes as unknown[]).filter((v): v is string => typeof v === 'string')
    : []

  return {
    index: typeof fields.defaultIndex === 'string' && fields.defaultIndex ? fields.defaultIndex : undefined,
    indexes: allowedIndexes.length > 0 ? allowedIndexes.join(',') : undefined,
    sourcetype: typeof fields.defaultSourcetype === 'string' && fields.defaultSourcetype ? fields.defaultSourcetype : undefined,
    source: typeof fields.defaultSource === 'string' && fields.defaultSource ? fields.defaultSource : undefined,
    description: typeof fields.description === 'string' && fields.description ? fields.description : undefined,
    useACK: typeof fields.useACK === 'boolean' ? (fields.useACK ? '1' : '0') : undefined,
  }
}

/** Every index a token routes to (defaultIndex + allowedIndexes), de-duplicated. */
function collectReferencedIndexes(sections: Array<{ fields: Record<string, unknown> }>): string[] {
  const set = new Set<string>()
  for (const section of sections) {
    const fields = section.fields
    if (typeof fields.defaultIndex === 'string' && fields.defaultIndex) set.add(fields.defaultIndex)
    if (Array.isArray(fields.allowedIndexes)) {
      for (const v of fields.allowedIndexes) if (typeof v === 'string' && v) set.add(v)
    }
  }
  return [...set]
}

/**
 * Live index names on the target (`data/indexes`, all datatypes, unpaginated).
 * Returns null when the list can't be read so the caller skips validation and
 * lets the real deploy surface any connectivity/auth error.
 */
async function listIndexNames(baseUrl: string, auth: Record<string, string>): Promise<Set<string> | null> {
  try {
    const data = await getJson<{ entry?: Array<{ name?: string }> }>(
      baseUrl,
      auth,
      '/services/data/indexes?datatype=all&count=0',
      15000,
    )
    const names = new Set<string>()
    for (const e of data.entry ?? []) if (typeof e.name === 'string' && e.name) names.add(e.name)
    return names
  } catch {
    return null
  }
}
