import type { DeployContext, DeployResult } from '@veltrixsecops/app-sdk'
import { buildSplunkUrl, buildAuthHeader, getEntityContent, postForm, splunkRequest } from '../../lib/splunkApi'

/**
 * Deploy HEC token configuration via the REST API. Tokens live in the
 * splunk_httpinput app, so management goes through the servicesNS path:
 *   create:  POST   /servicesNS/admin/splunk_httpinput/data/inputs/http           (name=<token>)
 *   update:  POST   /servicesNS/admin/splunk_httpinput/data/inputs/http/<token>
 *   enable:  POST   .../http/<token>/enable    disable: .../http/<token>/disable
 *
 * Canvas → Splunk REST parameter mapping:
 *   defaultIndex      → index       (default index for events)
 *   allowedIndexes    → indexes     (comma-separated allow-list)
 *   defaultSourcetype → sourcetype
 *   defaultSource     → source
 *   description       → description
 *   useACK            → useACK      (1/0 — indexer acknowledgment)
 *   enabled           → enable/disable sub-endpoints
 *
 * The token VALUE is generated by Splunk and intentionally NOT included in
 * artifacts or rollback data — operators read it from Splunk directly.
 */

export const HEC_BASE_PATH = '/servicesNS/admin/splunk_httpinput/data/inputs/http'

/** Token settings snapshotted for rollback. */
const ROLLBACK_KEYS = ['index', 'indexes', 'sourcetype', 'source', 'description', 'useACK', 'disabled'] as const

export default async function deploy(ctx: DeployContext): Promise<DeployResult> {
  const { component, credential, connectivity, canvas } = ctx

  if (!credential || !connectivity) {
    return { success: false, message: 'Missing credential or connectivity for HEC token deployment' }
  }

  const baseUrl = buildSplunkUrl(component, connectivity)
  const auth = buildAuthHeader(credential)
  const rollbackSnapshot: Record<string, unknown>[] = []
  const createdTokens: string[] = []
  const deployedTokens: string[] = []

  try {
    for (const section of canvas.sections) {
      const fields = section.fields
      const tokenName = fields.name as string
      if (!tokenName) continue

      const tokenPath = `${HEC_BASE_PATH}/${encodeURIComponent(tokenName)}`

      // Capture current state for rollback (token value excluded — it never changes)
      const existing = await getEntityContent(baseUrl, auth, tokenPath)
      if (existing) {
        const snapshot: Record<string, unknown> = { name: tokenName }
        for (const key of ROLLBACK_KEYS) {
          if (existing[key] !== undefined) snapshot[key] = existing[key]
        }
        rollbackSnapshot.push(snapshot)
      }

      const payload = buildTokenPayload(fields)

      if (existing) {
        await postForm(baseUrl, auth, tokenPath, payload)
      } else {
        await postForm(baseUrl, auth, HEC_BASE_PATH, { name: tokenName, ...payload })
        createdTokens.push(tokenName)
      }

      // Enabled state is toggled through dedicated sub-endpoints
      if (typeof fields.enabled === 'boolean') {
        const action = fields.enabled ? 'enable' : 'disable'
        await splunkRequest(`${baseUrl}${tokenPath}/${action}`, { method: 'POST', headers: auth })
      }

      deployedTokens.push(tokenName)
    }

    return {
      success: true,
      message: `Deployed ${deployedTokens.length} HEC token(s): ${deployedTokens.join(', ')}`,
      artifacts: { deployedTokens, createdTokens },
      rollbackData: { previousState: rollbackSnapshot, createdTokens },
    }
  } catch (error) {
    return {
      success: false,
      message: `HEC token deployment failed after ${deployedTokens.length} token(s): ${error instanceof Error ? error.message : 'Unknown error'}`,
      artifacts: { deployedTokens, createdTokens, failedAt: canvas.sections[deployedTokens.length]?.fields?.name },
      rollbackData: { previousState: rollbackSnapshot, createdTokens },
    }
  }
}

/** Map canvas fields to Splunk REST parameters. */
function buildTokenPayload(fields: Record<string, unknown>): Record<string, string | undefined> {
  const allowedIndexes = Array.isArray(fields.allowedIndexes)
    ? (fields.allowedIndexes as unknown[]).filter((v): v is string => typeof v === 'string')
    : []

  return {
    index: typeof fields.defaultIndex === 'string' && fields.defaultIndex ? fields.defaultIndex : undefined,
    indexes: allowedIndexes.length > 0 ? allowedIndexes.join(',') : undefined,
    sourcetype: typeof fields.defaultSourcetype === 'string' && fields.defaultSourcetype ? fields.defaultSourcetype : undefined,
    source: typeof fields.defaultSource === 'string' && fields.defaultSource ? fields.defaultSource : undefined,
    description: typeof fields.description === 'string' && fields.description ? fields.description : undefined,
    useACK: typeof fields.useACK === 'boolean' ? (fields.useACK ? '1' : '0') : undefined,
  }
}
