import type { PipelineContext, ValidationResult } from '@veltrixsecops/app-sdk'

/**
 * Validate Splunk HTTP Event Collector (HEC) token configurations.
 *
 * Tokens are managed through /servicesNS/admin/splunk_httpinput/data/inputs/http.
 * The token VALUE is generated by Splunk on creation — the canvas only
 * declares the token name and its ingestion settings.
 *
 * Rules:
 *   - Token names appear in REST URLs; this app restricts them to
 *     letters, digits, underscores, dots and hyphens (platform guardrail).
 *   - defaultIndex / allowedIndexes entries must follow Splunk index
 *     naming rules (numbers, lowercase letters, underscores, hyphens;
 *     not starting with underscore/hyphen).
 *   - When allowedIndexes is set, defaultIndex must be included in it,
 *     otherwise Splunk rejects every event sent with the default index.
 */

const TOKEN_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_.-]*$/
const MAX_TOKEN_NAME_LENGTH = 80
const INDEX_NAME_PATTERN = /^[a-z0-9][a-z0-9_-]*$/

export default async function validate(ctx: PipelineContext): Promise<ValidationResult> {
  const errors: ValidationResult['errors'] = []
  const warnings: ValidationResult['warnings'] = []

  const sections = ctx.canvas.sections
  if (!sections || sections.length === 0) {
    errors.push({ field: 'sections', message: 'Canvas has no HEC token definitions', code: 'empty_canvas' })
    return { valid: false, errors, warnings }
  }

  const tokenNames = new Set<string>()

  for (const section of sections) {
    const fields = section.fields || {}
    const prefix = section.name

    // --- Token name -----------------------------------------------------------
    const name = fields.name as string | undefined
    if (!name || typeof name !== 'string' || name.trim().length === 0) {
      errors.push({ field: `${prefix}.name`, message: 'Token name is required', code: 'required' })
    } else {
      if (!TOKEN_NAME_PATTERN.test(name)) {
        errors.push({
          field: `${prefix}.name`,
          message: 'Token name may contain only letters, digits, underscores, dots, and hyphens, and must start with a letter or digit',
          code: 'invalid_format',
        })
      }
      if (name.length > MAX_TOKEN_NAME_LENGTH) {
        errors.push({ field: `${prefix}.name`, message: `Token name must be ${MAX_TOKEN_NAME_LENGTH} characters or fewer`, code: 'max_length' })
      }
      if (tokenNames.has(name)) {
        errors.push({ field: `${prefix}.name`, message: `Duplicate token name: "${name}"`, code: 'duplicate' })
      }
      tokenNames.add(name)
    }

    // --- Allowed indexes ---------------------------------------------------------
    const allowedIndexes = fields.allowedIndexes as string[] | undefined
    if (allowedIndexes !== undefined && !Array.isArray(allowedIndexes)) {
      errors.push({ field: `${prefix}.allowedIndexes`, message: 'Allowed indexes must be an array', code: 'invalid_type' })
    } else if (Array.isArray(allowedIndexes)) {
      for (const idx of allowedIndexes) {
        if (typeof idx !== 'string' || !INDEX_NAME_PATTERN.test(idx)) {
          errors.push({
            field: `${prefix}.allowedIndexes`,
            message: `"${idx}" is not a valid Splunk index name`,
            code: 'invalid_format',
          })
        }
      }
      if (allowedIndexes.length === 0) {
        warnings.push({
          field: `${prefix}.allowedIndexes`,
          message: 'Token can write to any index the HEC user can access — restrict allowed indexes for least privilege',
          code: 'unrestricted_indexes',
        })
      }
    } else {
      warnings.push({
        field: `${prefix}.allowedIndexes`,
        message: 'Token can write to any index the HEC user can access — restrict allowed indexes for least privilege',
        code: 'unrestricted_indexes',
      })
    }

    // --- Default index ------------------------------------------------------------
    const defaultIndex = fields.defaultIndex as string | undefined
    if (defaultIndex !== undefined && defaultIndex !== '') {
      if (typeof defaultIndex !== 'string' || !INDEX_NAME_PATTERN.test(defaultIndex)) {
        errors.push({ field: `${prefix}.defaultIndex`, message: 'Default index is not a valid Splunk index name', code: 'invalid_format' })
      } else if (Array.isArray(allowedIndexes) && allowedIndexes.length > 0 && !allowedIndexes.includes(defaultIndex)) {
        errors.push({
          field: `${prefix}.defaultIndex`,
          message: `Default index "${defaultIndex}" is not in the allowed indexes list — Splunk will reject events sent without an explicit index`,
          code: 'index_not_allowed',
        })
      }
    } else {
      warnings.push({
        field: `${prefix}.defaultIndex`,
        message: 'No default index set — events without an explicit index go to the Splunk default index (main)',
        code: 'no_default_index',
      })
    }

    // --- Indexer acknowledgment ------------------------------------------------------
    const useACK = fields.useACK as boolean | undefined
    if (useACK !== undefined && typeof useACK !== 'boolean') {
      errors.push({ field: `${prefix}.useACK`, message: 'useACK must be a boolean', code: 'invalid_type' })
    }
  }

  return { valid: errors.length === 0, errors, warnings }
}
