import type { CanvasSnapshot, PipelineContext, ValidationResult } from '@veltrixsecops/app-sdk'

// --- Vault Transit secrets engine KEY CONFIGURATION constraints --------------
//
// See: https://developer.hashicorp.com/vault/api-docs/secret/transit#create-key
//  and https://developer.hashicorp.com/vault/api-docs/secret/transit#update-key-configuration
//
// THE LINE THIS CONFIG TYPE DRAWS: it manages a transit key's EXISTENCE and
// CONFIGURATION ONLY — type, derivation/convergence flags, exportability,
// deletion policy, key-version bounds, and rotation cadence. The actual key
// BYTES are generated by Vault, live only inside Vault, and are NEVER returned
// by any read endpoint this app calls (Vault's own docs confirm raw key
// material is never returned by GET {mount}/keys/{name}). This config type
// never encrypts, decrypts, signs, rotates, or exports — those are one-shot
// cryptographic OPERATIONS, not declarative config, and are out of scope.

/** A mount path may contain letters, digits and the characters _ . / - . */
export const MOUNT_PATH_PATTERN = /^[A-Za-z0-9_./-]+$/

/** A transit key name may contain letters, digits and the characters _ . - . */
export const KEY_NAME_PATTERN = /^[A-Za-z0-9_.-]+$/

/** The `type` values Vault's transit key creation accepts. IMMUTABLE once created. */
export const TRANSIT_KEY_TYPES = [
  'aes128-gcm96',
  'aes256-gcm96',
  'chacha20-poly1305',
  'ed25519',
  'ecdsa-p256',
  'ecdsa-p384',
  'ecdsa-p521',
  'rsa-2048',
  'rsa-3072',
  'rsa-4096',
  'hmac',
] as const

/** Only the "hmac" type accepts a variable `key_size`. */
export const HMAC_KEY_TYPE = 'hmac'

/**
 * A Vault duration is either a plain whole number of seconds or a Go-style
 * duration made of `<number><unit>` runs (s/m/h/d), e.g. "0", "1h", "720h".
 * (Kept local so this config type stays self-contained — mirrors secret-mounts.)
 */
export function isValidVaultDuration(value: string): boolean {
  const v = value.trim()
  if (!v) return false
  if (/^\d+$/.test(v)) return true
  return /^(?:\d+(?:\.\d+)?(?:s|m|h|d))+$/i.test(v)
}

/** Parse a Vault duration to seconds, or undefined when it cannot be parsed. */
export function parseDurationSeconds(value: string | undefined): number | undefined {
  if (value === undefined) return undefined
  const v = value.trim()
  if (!v) return undefined
  if (/^\d+$/.test(v)) return Number(v)
  const re = /(\d+(?:\.\d+)?)(s|m|h|d)/gi
  let total = 0
  let matched = false
  let m: RegExpExecArray | null
  while ((m = re.exec(v)) !== null) {
    matched = true
    const n = parseFloat(m[1])
    const unit = m[2].toLowerCase()
    total += unit === 'd' ? n * 86400 : unit === 'h' ? n * 3600 : unit === 'm' ? n * 60 : n
  }
  return matched ? total : undefined
}

// --- Spec extraction shared by deploy / rollback / healthCheck / drift --------

export interface TransitKeySpec {
  sectionName: string
  /** Transit secrets engine mount path (e.g. "transit"). Part of the identity. */
  mount: string
  /** Key name — the {name} in {mount}/keys/{name}. Part of the identity. */
  name: string

  // --- CREATE-ONLY (immutable once the key exists) ---
  type: string
  convergentEncryption: boolean
  derived: boolean
  keySize?: number

  // --- tunable via {mount}/keys/{name}/config ---
  /** Once true, Vault will not allow it to be set back to false ("write-once"). */
  exportable: boolean
  /** Once true, Vault will not allow it to be set back to false ("write-once"). */
  allowPlaintextBackup: boolean
  deletionAllowed: boolean
  minDecryptionVersion?: number
  minEncryptionVersion?: number
  /** A Vault duration, or "0" to disable automatic rotation. */
  autoRotatePeriod?: string
}

/**
 * Shape of a key returned by GET {mount}/keys/{name} (under `data`). `keys` maps
 * version number → CREATION TIMESTAMP ONLY — Vault's docs state plainly that
 * this is not the key material itself, and this app never reads or diffs it.
 */
export interface LiveTransitKey {
  name?: string
  type?: string
  derived?: boolean
  convergent_encryption?: boolean
  exportable?: boolean
  allow_plaintext_backup?: boolean
  deletion_allowed?: boolean
  min_decryption_version?: number
  min_encryption_version?: number
  auto_rotate_period?: number
  /** version → creation timestamp. NEVER the key bytes. Not read by this app. */
  keys?: Record<string, unknown>
}

function optionalString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined
}

/** Coerce a numeric field (a `number` input or text) to a number; NaN when unparseable. */
export function optionalNumber(value: unknown): number | undefined {
  if (value === undefined || value === null || value === '') return undefined
  if (typeof value === 'number') return Number.isFinite(value) ? value : NaN
  const n = Number(String(value).trim())
  return Number.isNaN(n) ? NaN : n
}

/** Coerce a checkbox value to a boolean, falling back to a default when unset. */
export function coerceBoolean(value: unknown, fallback: boolean): boolean {
  if (value === undefined || value === null || value === '') return fallback
  if (typeof value === 'boolean') return value
  if (typeof value === 'string') return value.toLowerCase() !== 'false' && value !== '0'
  return Boolean(value)
}

/** Trim and strip surrounding slashes so a mount reference is canonical. */
export function normalizeMountPath(raw: unknown): string {
  if (typeof raw !== 'string') return ''
  return raw.trim().replace(/^\/+|\/+$/g, '')
}

/** The composite key identity "mount/name" — the dedup + match key. */
export function keyKey(mount: string, name: string): string {
  return `${mount}/${name}`
}

/** Each canvas section describes one Vault transit key. */
export function extractTransitKeySpecs(canvas: CanvasSnapshot): TransitKeySpec[] {
  return (canvas.sections ?? []).map((section) => {
    const fields = section.fields ?? {}
    return {
      sectionName: section.name,
      mount: normalizeMountPath(fields.mount),
      name: typeof fields.name === 'string' ? fields.name.trim() : '',

      type: typeof fields.type === 'string' ? fields.type.trim().toLowerCase() : '',
      convergentEncryption: coerceBoolean(fields.convergentEncryption, false),
      derived: coerceBoolean(fields.derived, false),
      keySize: optionalNumber(fields.keySize),

      exportable: coerceBoolean(fields.exportable, false),
      allowPlaintextBackup: coerceBoolean(fields.allowPlaintextBackup, false),
      deletionAllowed: coerceBoolean(fields.deletionAllowed, false),
      minDecryptionVersion: optionalNumber(fields.minDecryptionVersion),
      minEncryptionVersion: optionalNumber(fields.minEncryptionVersion),
      autoRotatePeriod: optionalString(fields.autoRotatePeriod),
    }
  })
}

// --- Validate handler ---------------------------------------------------------

/**
 * Validate transit key configurations against Vault's constraints (no
 * network): mount and name are required and URL-safe, the composite (mount,
 * name) — the key's identity — is unique per canvas, type is one of Vault's
 * known key types, convergent_encryption requires derived, key_size is only
 * meaningful for hmac, min_decryption/encryption_version are non-negative
 * whole numbers, and auto_rotate_period is either "0" (disabled) or at least
 * one hour (Vault's documented minimum).
 */
export default async function validate(ctx: PipelineContext): Promise<ValidationResult> {
  const errors: ValidationResult['errors'] = []
  const warnings: ValidationResult['warnings'] = []

  const sections = ctx.canvas.sections
  if (!sections || sections.length === 0) {
    errors.push({ field: 'sections', message: 'Canvas has no configuration sections', code: 'empty_canvas' })
    return { valid: false, errors, warnings }
  }

  const specs = extractTransitKeySpecs(ctx.canvas)
  const seenKeys = new Set<string>()

  for (const spec of specs) {
    const prefix = spec.sectionName

    // mount — required, URL-safe charset
    if (!spec.mount) {
      errors.push({ field: `${prefix}.mount`, message: 'Transit mount path is required (e.g. "transit")', code: 'required' })
    } else if (!MOUNT_PATH_PATTERN.test(spec.mount)) {
      errors.push({
        field: `${prefix}.mount`,
        message: 'Mount path may contain only letters, digits, and the characters _ . / -',
        code: 'invalid_mount',
      })
    }

    // name — required, safe charset
    if (!spec.name) {
      errors.push({ field: `${prefix}.name`, message: 'Key name is required', code: 'required' })
    } else if (!KEY_NAME_PATTERN.test(spec.name)) {
      errors.push({
        field: `${prefix}.name`,
        message: 'Key name may contain only letters, digits, and the characters _ . -',
        code: 'invalid_name',
      })
    }

    // (mount, name) is the key's identity — dedupe on the composite key.
    if (spec.mount && spec.name) {
      const key = keyKey(spec.mount, spec.name)
      if (seenKeys.has(key)) {
        errors.push({
          field: `${prefix}.name`,
          message: `Duplicate transit key "${key}" — each (mount, name) key may only be declared once per canvas`,
          code: 'duplicate_key',
        })
      }
      seenKeys.add(key)
    }

    // type — required (IMMUTABLE once created); one of the known key types
    if (!spec.type) {
      errors.push({
        field: `${prefix}.type`,
        message: `Key type is required (one of ${TRANSIT_KEY_TYPES.join(', ')})`,
        code: 'required',
      })
    } else if (!(TRANSIT_KEY_TYPES as readonly string[]).includes(spec.type)) {
      errors.push({
        field: `${prefix}.type`,
        message: `Key type must be one of ${TRANSIT_KEY_TYPES.join(', ')}`,
        code: 'invalid_type',
      })
    }

    // convergent_encryption REQUIRES derived (Vault rejects the combination otherwise).
    if (spec.convergentEncryption && !spec.derived) {
      errors.push({
        field: `${prefix}.convergentEncryption`,
        message: 'Convergent Encryption requires Derived to also be enabled',
        code: 'convergent_requires_derived',
      })
    }

    // keySize — only meaningful for hmac; warn (not error) when set elsewhere.
    if (spec.keySize !== undefined) {
      if (Number.isNaN(spec.keySize) || !Number.isInteger(spec.keySize) || spec.keySize < 32 || spec.keySize > 512) {
        errors.push({
          field: `${prefix}.keySize`,
          message: 'Key size must be a whole number of bytes between 32 and 512 (hmac keys only)',
          code: 'invalid_key_size',
        })
      }
      if (spec.type && spec.type !== HMAC_KEY_TYPE) {
        warnings.push({
          field: `${prefix}.keySize`,
          message: `Key size is only meaningful for the "hmac" type — it is ignored for a "${spec.type}" key`,
          code: 'key_size_ignored',
        })
      }
    }

    // min_decryption_version / min_encryption_version — non-negative whole numbers.
    for (const [field, value] of [
      ['minDecryptionVersion', spec.minDecryptionVersion],
      ['minEncryptionVersion', spec.minEncryptionVersion],
    ] as const) {
      if (value === undefined) continue
      if (Number.isNaN(value) || !Number.isInteger(value) || value < 0) {
        errors.push({ field: `${prefix}.${field}`, message: `${field} must be a non-negative whole number`, code: 'invalid_version' })
      }
    }

    // autoRotatePeriod — "0" (disabled) or at least one hour.
    if (spec.autoRotatePeriod !== undefined) {
      if (!isValidVaultDuration(spec.autoRotatePeriod)) {
        errors.push({
          field: `${prefix}.autoRotatePeriod`,
          message: 'Auto rotate period must be a Vault duration (e.g. "720h") or "0" to disable',
          code: 'invalid_duration',
        })
      } else {
        const seconds = parseDurationSeconds(spec.autoRotatePeriod)
        if (seconds !== undefined && seconds !== 0 && seconds < 3600) {
          errors.push({
            field: `${prefix}.autoRotatePeriod`,
            message: 'Auto rotate period must be "0" (disabled) or at least 1 hour',
            code: 'auto_rotate_too_short',
          })
        }
      }
    }
  }

  return { valid: errors.length === 0, errors, warnings }
}
