import type { ConfigFixture } from '../../../lib/__tests__/configFixture'

/** The live VIP maps the public address to a DIFFERENT internal host, and
 *  returns its addresses in the `[{ range }]` form a `get` uses. Repointed
 *  static NAT is the highest-consequence drift this app can see. */
export const fixture: ConfigFixture = {
  id: 'firewall-vips',
  objectPath: '/obj/firewall/vip',
  checkName: 'fmg-firewall-vip',
  name: 'vip-web',
  item: {
    id: 'item-1',
    name: 'vip-web',
    fields: {
      name: 'vip-web',
      extintf: 'port1',
      extip: '203.0.113.50',
      mappedip: '10.0.50.10',
      portforward: 'enable',
      protocol: 'tcp',
      extport: '443',
      mappedport: '8443',
      arpReply: 'enable',
      comment: 'Public web VIP',
    },
  },
  body: {
    name: 'vip-web',
    type: 'static-nat',
    extip: '203.0.113.50',
    mappedip: '10.0.50.10',
    portforward: 'enable',
    'arp-reply': 'enable',
    extintf: 'port1',
    protocol: 'tcp',
    extport: '443',
    mappedport: '8443',
    comment: 'Public web VIP',
  },
  livePrior: {
    name: 'vip-web',
    type: 'static-nat',
    extintf: ['port1'],
    extip: [{ range: '203.0.113.50' }],
    mappedip: [{ range: '10.0.50.99' }],
    extport: '443',
    mappedport: '8443',
    portforward: 'enable',
    protocol: 'tcp',
    'arp-reply': 'enable',
    comment: 'Public web VIP',
  },
  priorSnapshot: {
    name: 'vip-web',
    type: 'static-nat',
    extip: '203.0.113.50',
    mappedip: '10.0.50.99',
    extintf: 'port1',
    extport: '443',
    mappedport: '8443',
    portforward: 'enable',
    'arp-reply': 'enable',
    comment: 'Public web VIP',
    protocol: 'tcp',
  },
  liveInSync: {
    name: 'vip-web',
    type: 'static-nat',
    extintf: 'port1',
    extip: '203.0.113.50',
    mappedip: '10.0.50.10',
    extport: '443',
    mappedport: '8443',
    portforward: 'enable',
    protocol: 'tcp',
    'arp-reply': 'enable',
    comment: 'Public web VIP',
  },
  driftField: 'vip-web.mappedip',
  deploySuccess: 'Deployed 1 firewall virtual IP(s)',
  deployFailurePrefix: 'Some virtual IPs failed',
  rollbackPrefix: 'Rolled back firewall virtual IPs',
}
