// Render a dataflow model as DATAFLOW.md — request-routing view: a lifecycle
// map (how operations connect) + one Mermaid sequence diagram per operation
// (how a request moves hop-by-hop to completion). Renders natively on GitHub.

import { buildFlows } from './flows.mjs'

// Mermaid message text: strip chars that break the parser; keep it on one line.
function msg(s) {
  return String(s).replace(/[:;#]/g, '').replace(/\|/g, '/').replace(/\n/g, ' ').trim()
}
function nodeLabel(s) {
  return String(s).replace(/"/g, '').replace(/[[\]{}]/g, '')
}
const nid = (s) => s.replace(/[^a-zA-Z0-9]/g, '_')

const SHAPES = {
  state: ['([', '])'],
  act: ['[', ']'],
  pre: ['[/', '/]'],
  gate: ['{{', '}}'],
  default: ['(', ')'],
}

function lifecycleDiagram(lc) {
  const lines = ['```mermaid', 'flowchart LR']
  for (const n of lc.nodes) {
    const shape = SHAPES[n.kind] ?? SHAPES.default
    lines.push(`  ${nid(n.id)}${shape[0]}"${nodeLabel(n.label)}"${shape[1]}`)
  }
  const present = new Set(lc.nodes.map((n) => n.id))
  for (const [a, b, label] of lc.edges) {
    if (!present.has(a) || !present.has(b)) continue
    lines.push(label ? `  ${nid(a)} -->|"${nodeLabel(label)}"| ${nid(b)}` : `  ${nid(a)} --> ${nid(b)}`)
  }
  lines.push('  classDef state fill:#eff6ff,stroke:#3b82f6,color:#1e3a8a,font-weight:bold;')
  lines.push('  classDef act fill:#ecfeff,stroke:#0ea5e9,color:#0c4a6e;')
  lines.push('  classDef gate fill:#fffbeb,stroke:#f59e0b,color:#78350f;')
  const byKind = (k) => lc.nodes.filter((n) => n.kind === k).map((n) => nid(n.id))
  if (byKind('state').length) lines.push(`  class ${byKind('state').join(',')} state;`)
  if (byKind('act').length) lines.push(`  class ${byKind('act').join(',')} act;`)
  if (byKind('gate').length) lines.push(`  class ${byKind('gate').join(',')} gate;`)
  lines.push('```')
  return lines.join('\n')
}

function environmentsDiagram(envs) {
  const lines = ['```mermaid', 'flowchart LR']
  envs.forEach((e, i) => {
    lines.push(`  E${i}(["${nodeLabel(e.name)}"])`)
    if (i > 0) {
      const label = envs[i].approval ? 'promote · approval ✋' : 'promote'
      lines.push(`  E${i - 1} -->|"${label}"| E${i}`)
    }
  })
  lines.push('```')
  return lines.join('\n')
}

function sequenceDiagram(op, participants) {
  const lines = ['```mermaid', 'sequenceDiagram', '  autonumber']
  for (const key of op.participants) {
    const p = participants[key]
    lines.push(`  participant ${key} as ${nodeLabel(p.name)}`)
  }
  for (const s of op.steps) {
    const arrow = s.dashed ? '-->>' : '->>'
    lines.push(`  ${s.from}${arrow}${s.to}: ${msg(s.text)}`)
    if (s.note) lines.push(`  Note over ${s.to}: ${msg(s.note)}`)
  }
  lines.push('```')
  return lines.join('\n')
}

export function renderMarkdown(model) {
  const flows = buildFlows(model)
  const md = []
  md.push(`# ${model.icon ? model.icon + ' ' : ''}${model.name} — Request Flows`)
  md.push('')
  md.push(`> How a request is routed through the system — from the moment you act to when it reaches completion. **Auto-generated** from \`manifest.yaml\` (regenerate via \`scripts/dataflow/generate.mjs\`).`)
  md.push('')
  md.push(`**App:** \`${model.id}\` · **Category:** ${model.category || '—'} · **Version:** ${model.version || '—'}  `)
  md.push(
    `**Operations:** ${flows.operations.map((o) => o.title.replace(/^(Deploy|Detect|Roll|Test).*/, (m) => m)).join(' · ')}  `,
  )
  md.push(`Talks to **${model.name} API**${model.requiresCredential ? ' · credentials via the Credential Vault (`ctx.resolveConnection`)' : ''}${model.requiresConnectivity ? ' · reachable over `ctx.remote`' : ''}.`)
  md.push('')
  md.push('Every operation authorizes against **RBAC** first; writes pass a **human approval gate** (enforced for production); credentials are **environment-scoped** and resolved per request.')
  md.push('')
  md.push('## Lifecycle — how operations connect')
  md.push('')
  md.push('Where a config goes from authoring to steady state, and how each request type feeds the next.')
  md.push('')
  md.push(lifecycleDiagram(flows.lifecycle))
  md.push('')
  md.push('## Environments & promotion')
  md.push('')
  md.push('Config is deployed per environment; connections are environment-scoped. Promotion to production passes the approval gate.')
  md.push('')
  md.push(environmentsDiagram(flows.environments))
  md.push('')
  md.push('## Request flows — how each one reaches completion')
  md.push('')
  for (const op of flows.operations) {
    md.push(`### ${op.title}`)
    md.push('')
    md.push(`*${op.when}*  `)
    md.push(`<sub>Applies to: ${op.appliesTo}.</sub>`)
    md.push('')
    md.push(sequenceDiagram(op, flows.participants))
    md.push('')
  }
  md.push('---')
  md.push('')
  md.push('<sub>Generated by `scripts/dataflow/generate.mjs`. Solid arrow = call ▶ · dashed = return ◀.</sub>')
  md.push('')
  return md.join('\n')
}
