// Render a dataflow model as DATAFLOW.md — a Mermaid diagram (renders natively
// on the GitHub repo file view) plus per-family capability tables.

const check = (on) => (on ? '✅' : '—')

// Mermaid node text is wrapped in quotes; strip the few chars that break parsing.
function mermaidLabel(s) {
  return String(s).replace(/"/g, '').replace(/[[\]{}]/g, '').replace(/\|/g, '/')
}

function familyNodeId(i) {
  return `F${i}`
}

function diagram(model) {
  const vendorFamilies = model.families.filter((f) => !f.isConnection)
  const lines = []
  lines.push('```mermaid')
  lines.push('flowchart LR')
  lines.push(`  CANVAS["Config Canvas"] --> PIPE["Pipeline<br/>validate · deploy · drift · rollback"]`)
  lines.push(`  PIPE -->|"deploy · write ▶"| APP["${mermaidLabel(model.name)}<br/><small>SDK ctx · adapters</small>"]`)
  lines.push(`  APP -->|"drift · read ◀"| PIPE`)
  if (model.requiresCredential) {
    lines.push(`  VAULT[("Credential Vault")] -.->|resolveConnection| APP`)
  }
  if (model.requiresConnectivity) {
    lines.push(`  REMOTE[("Network / ZTNA")] -.->|ctx.remote| APP`)
  }
  vendorFamilies.forEach((f, i) => {
    const id = familyNodeId(i)
    lines.push(`  APP --> ${id}["${mermaidLabel(f.name)}<br/><small>${f.types.length} type${f.types.length === 1 ? '' : 's'}</small>"]`)
  })
  lines.push('')
  lines.push('  classDef platform fill:#eff6ff,stroke:#3b82f6,color:#1e3a8a;')
  lines.push('  classDef app fill:#1e293b,stroke:#0ea5e9,color:#f8fafc;')
  lines.push('  classDef vendor fill:#fef2f2,stroke:#ef4444,color:#7f1d1d;')
  lines.push('  classDef seam fill:#f1f5f9,stroke:#94a3b8,color:#334155;')
  lines.push('  class CANVAS,PIPE platform;')
  lines.push('  class APP app;')
  if (model.requiresCredential || model.requiresConnectivity) lines.push('  class VAULT,REMOTE seam;')
  lines.push(`  class ${vendorFamilies.map((_, i) => familyNodeId(i)).join(',')} vendor;`)
  lines.push('```')
  return lines.join('\n')
}

function familyTables(model) {
  const out = []
  for (const f of model.families) {
    const heading = f.isConnection ? `${f.name} (connectivity)` : `${f.name} (${f.types.length} type${f.types.length === 1 ? '' : 's'})`
    out.push(`### ${heading}`)
    out.push('')
    out.push('| Config type | Deploy ▶ | Drift ◀ | Rollback | Status |')
    out.push('|---|:--:|:--:|:--:|:--:|')
    for (const t of f.types) {
      out.push(`| ${t.name} \`${t.id}\` | ${check(t.caps.deploy)} | ${check(t.caps.drift)} | ${check(t.caps.rollback)} | ${check(t.caps.status || t.caps.health)} |`)
    }
    out.push('')
  }
  return out.join('\n')
}

export function renderMarkdown(model) {
  const c = model.counts
  const md = []
  md.push(`# ${model.icon ? model.icon + ' ' : ''}${model.name} — Dataflow`)
  md.push('')
  md.push(`> How configuration flows between the Veltrix platform, this app, and the ${model.name} APIs. **Auto-generated** from \`manifest.yaml\` — do not edit by hand (regenerate via \`scripts/dataflow/generate.mjs\`).`)
  md.push('')
  md.push(
    `**App:** \`${model.id}\` · **Category:** ${model.category || '—'} · **Version:** ${model.version || '—'}  `,
  )
  md.push(
    `**${c.vendorTypes} config types** across **${c.families} API families** · ${c.deployable} deployable · ${c.driftable} drift-detected · ${c.rollbackable} rollback-capable`,
  )
  md.push('')
  md.push('## Flow')
  md.push('')
  md.push(diagram(model))
  md.push('')
  md.push('- **Deploy ▶** — the pipeline validates a canvas and writes it to the vendor API (`deploy` handler).')
  md.push('- **Drift ◀** — the app reads live vendor state and reconciles it against the canvas (`driftDetect` handler).')
  if (model.requiresCredential) md.push('- **Credential Vault** — tenant credentials are resolved per request via `ctx.resolveConnection` — never held by the app.')
  if (model.requiresConnectivity) md.push('- **Network / ZTNA** — reaches the target over `ctx.remote` (managed connectivity).')
  md.push('')
  md.push('## Config types by API family')
  md.push('')
  md.push(familyTables(model))
  md.push('---')
  md.push('')
  md.push('<sub>Generated by `scripts/dataflow/generate.mjs`. Legend: ✅ handler present · — not applicable.</sub>')
  md.push('')
  return md.join('\n')
}
