// deploy for zpa-provisioning-keys.
//
// Specific to this config type, and the reason it is the longest deploy in the
// app: THREE reads precede every write. The component group name is resolved
// against a collection chosen by the association type (/appConnectorGroup for
// CONNECTOR_GRP, /serviceEdgeGroup for SERVICE_EDGE_GRP), the enrollment
// certificate name against the **v2** /enrollmentCert endpoint (falling back to
// v1 on older tenants), and only then is the key list matched by name. CRUD
// lives under /associationType/{type}/provisioningKey, so identity is the
// (association_type, name) pair. maxUsage goes on the wire as a STRING.
//
// And the part no other config type in this app has: the key VALUE is a SECRET.
// ZPA returns it on create and on every listing; it must never reach a result
// message, an artifact, rollbackData or a request body.

import test from 'node:test'
import assert from 'node:assert/strict'
import deploy from '../deploy'
import {
  TOKEN,
  ZPA_CUSTOMER_ID,
  assertAuthenticatedFirst,
  bodyOf,
  created,
  deployContext,
  item,
  leaksSecret,
  notFound,
  ok,
  recordFetch,
  resourceWrites,
  routeFetch,
  serverError,
  zpaError,
  zpaList,
} from '../../../lib/__tests__/fakeZscaler'
import { registerDeployGuardContract } from '../../../lib/__tests__/zscalerContracts'
import { PROVISIONING_KEY, leaksProvisioningKey } from './keySecret'

const KEY = item('SJC Connector Key', {
  name: 'SJC Connector Key',
  association_type: 'CONNECTOR_GRP',
  max_usage: 5,
  component_group_name: 'San Jose Connectors',
  enrollment_cert_name: 'Connector',
  enabled: true,
})

const COMPONENT_GROUPS = zpaList([{ id: 'acg-1', name: 'San Jose Connectors' }])
const ENROLLMENT_CERTS = zpaList([{ id: 'cert-1', name: 'Connector' }])

/** The live key, deliberately unlike the canvas — and carrying the secret. */
const LIVE = {
  id: '216196257331370800',
  name: 'SJC Connector Key',
  maxUsage: '99',
  enabled: false,
  zcomponentId: 'acg-legacy',
  enrollmentCertId: 'cert-legacy',
  provisioningKey: PROVISIONING_KEY,
}

registerDeployGuardContract({
  label: 'zpa-provisioning-keys',
  handler: deploy,
  product: 'zpa',
  items: [KEY],
})

test('zpa-provisioning-keys deploy: resolves the group and the v2 enrollment cert, then creates the key', async () => {
  const { calls, restore } = recordFetch([
    TOKEN,
    COMPONENT_GROUPS,
    ENROLLMENT_CERTS,
    zpaList([]),
    created({ id: '216196257331371007', name: 'SJC Connector Key', provisioningKey: PROVISIONING_KEY }),
  ])
  try {
    const result = await deploy(deployContext([KEY]))

    const tenant = assertAuthenticatedFirst(assert, calls)
    assert.ok(
      tenant[0].url.includes(`/zpa/mgmtconfig/v1/admin/customers/${ZPA_CUSTOMER_ID}/appConnectorGroup`),
      `component group lookup hit ${tenant[0].url}`,
    )
    assert.ok(
      tenant[1].url.includes(`/zpa/mgmtconfig/v2/admin/customers/${ZPA_CUSTOMER_ID}/enrollmentCert`),
      `enrollment certificates are read on v2, but the lookup hit ${tenant[1].url}`,
    )
    assert.ok(
      tenant[2].url.includes(`/associationType/CONNECTOR_GRP/provisioningKey`),
      `key listing hit ${tenant[2].url}`,
    )
    assert.equal(tenant[3].method, 'POST')
    assert.ok(
      tenant[3].url.includes(
        `/zpa/mgmtconfig/v1/admin/customers/${ZPA_CUSTOMER_ID}/associationType/CONNECTOR_GRP/provisioningKey`,
      ),
      `create hit ${tenant[3].url}`,
    )

    const body = bodyOf(tenant[3])
    assert.equal(body?.name, 'SJC Connector Key')
    assert.equal(body?.maxUsage, '5', 'ZPA takes maxUsage as a string')
    assert.equal(body?.zcomponentId, 'acg-1', 'the component group NAME resolved to its live id')
    assert.equal(body?.enrollmentCertId, 'cert-1', 'the certificate NAME resolved to its live id')
    assert.equal(body?.enabled, true)
    assert.equal(body?.id, undefined, 'a create must not carry an id')
    assert.equal(body?.provisioningKey, undefined, 'the key value is generated by ZPA, never sent')

    assert.equal(result.success, true)
    assert.equal(
      calls.filter((c) => c.url.includes('/status/activate')).length,
      0,
      'ZPA applies immediately — there is nothing to activate',
    )

    const rollback = result.rollbackData as {
      previousState: Array<Record<string, unknown>>
      createdKeys: Array<Record<string, unknown>>
    }
    assert.deepEqual(rollback.previousState, [
      {
        name: 'SJC Connector Key',
        associationType: 'CONNECTOR_GRP',
        existed: false,
        id: '216196257331371007',
      },
    ])
    assert.deepEqual(rollback.createdKeys, [
      { id: '216196257331371007', associationType: 'CONNECTOR_GRP' },
    ])
    assert.equal(leaksSecret(result), false)
    assert.equal(
      leaksProvisioningKey(result),
      false,
      'the generated key value must not survive into the message, artifacts or rollback state',
    )
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: a SERVICE_EDGE_GRP key resolves the Service Edge group collection', async () => {
  const edgeKey = item('Edge Key', {
    name: 'Edge Key',
    association_type: 'SERVICE_EDGE_GRP',
    max_usage: 2,
    component_group_name: 'London Edges',
    enrollment_cert_name: 'Service Edge',
    enabled: true,
  })
  const { calls, restore } = recordFetch([
    TOKEN,
    zpaList([{ id: 'se-1', name: 'London Edges' }]),
    zpaList([{ id: 'cert-2', name: 'Service Edge' }]),
    zpaList([]),
    created({ id: '216196257331371008' }),
  ])
  try {
    const result = await deploy(deployContext([edgeKey]))

    const tenant = assertAuthenticatedFirst(assert, calls)
    assert.ok(tenant[0].url.includes('/serviceEdgeGroup'), `component group lookup hit ${tenant[0].url}`)
    assert.ok(tenant[2].url.includes('/associationType/SERVICE_EDGE_GRP/provisioningKey'))

    const body = bodyOf(tenant[3])
    assert.equal(body?.zcomponentId, 'se-1')
    assert.equal(body?.enrollmentCertId, 'cert-2')
    assert.equal(body?.maxUsage, '2')
    assert.equal(result.success, true)
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: falls back to the v1 enrollment cert endpoint when v2 is unavailable', async () => {
  const { calls, restore } = routeFetch([
    { url: /\/mgmtconfig\/v2\/.*\/enrollmentCert/, respond: notFound() },
    { url: /\/mgmtconfig\/v1\/.*\/enrollmentCert/, respond: ENROLLMENT_CERTS },
    { url: /\/appConnectorGroup/, respond: COMPONENT_GROUPS },
    { url: /\/provisioningKey/, method: 'GET', respond: zpaList([]) },
    { url: /\/provisioningKey/, method: 'POST', respond: created({ id: '216196257331371009' }) },
  ])
  try {
    const result = await deploy(deployContext([KEY]))

    assert.equal(result.success, true)
    assert.equal(
      calls.filter((c) => /\/mgmtconfig\/v1\/.*\/enrollmentCert/.test(c.url)).length > 0,
      true,
      'the v1 endpoint must actually be tried',
    )
    const body = bodyOf(resourceWrites(calls)[0])
    assert.equal(body?.enrollmentCertId, 'cert-1')
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: updates an existing key and records its LIVE prior scalars, never the secret', async () => {
  const { calls, restore } = recordFetch([
    TOKEN,
    COMPONENT_GROUPS,
    ENROLLMENT_CERTS,
    zpaList([LIVE]),
    ok({ id: LIVE.id }),
  ])
  try {
    const result = await deploy(deployContext([KEY]))

    const writes = resourceWrites(calls)
    assert.equal(writes.length, 1)
    assert.equal(writes[0].method, 'PUT', 'a key that exists is updated, not created')
    assert.ok(
      writes[0].url.includes(`/associationType/CONNECTOR_GRP/provisioningKey/${LIVE.id}`),
      `update hit ${writes[0].url}`,
    )

    const body = bodyOf(writes[0])
    assert.equal(body?.id, LIVE.id, 'the replace-style PUT must echo the id back')
    assert.equal(body?.maxUsage, '5')
    assert.equal(body?.enabled, true)
    assert.equal(body?.zcomponentId, 'acg-1')
    assert.equal(body?.enrollmentCertId, 'cert-1')
    assert.equal(
      leaksProvisioningKey(body),
      false,
      'the live key value must not be echoed back in the update body',
    )

    const rollback = result.rollbackData as {
      previousState: Array<{ existed: boolean; id: string; associationType: string; prior: Record<string, unknown> }>
    }
    const entry = rollback.previousState[0]
    assert.equal(entry.existed, true)
    assert.equal(entry.id, LIVE.id)
    assert.equal(entry.associationType, 'CONNECTOR_GRP', 'rollback needs it to rebuild the CRUD path')
    assert.equal(entry.prior.maxUsage, 99, 'the LIVE usage cap, not the desired one')
    assert.equal(entry.prior.enabled, false)
    assert.equal(entry.prior.zcomponentId, 'acg-legacy')
    assert.equal(entry.prior.enrollmentCertId, 'cert-legacy')
    assert.equal(
      leaksProvisioningKey(rollback),
      false,
      'rollback state must carry the scalars only — never the key value',
    )
    assert.equal(leaksProvisioningKey(result), false)
    assert.equal(leaksSecret(result), false)
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: refuses to write a key whose enrollment certificate does not exist', async () => {
  const { calls, restore } = recordFetch([
    TOKEN,
    COMPONENT_GROUPS,
    zpaList([{ id: 'cert-2', name: 'Service Edge' }]),
  ])
  try {
    const result = await deploy(deployContext([KEY]))

    assert.equal(result.success, false)
    assert.match(String(result.message), /Enrollment certificate "Connector".*was not found in the tenant/)
    assert.equal(resourceWrites(calls).length, 0, 'an unresolvable certificate must not be written around')
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: refuses to write a key whose component group does not exist', async () => {
  const { calls, restore } = recordFetch([TOKEN, zpaList([{ id: 'acg-9', name: 'Other Connectors' }])])
  try {
    const result = await deploy(deployContext([KEY]))

    assert.equal(result.success, false)
    assert.match(String(result.message), /App Connector group "San Jose Connectors".*was not found in the tenant/)
    assert.equal(resourceWrites(calls).length, 0)
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: a rejected write fails the deploy rather than throwing', async () => {
  const { restore } = recordFetch([
    TOKEN,
    COMPONENT_GROUPS,
    ENROLLMENT_CERTS,
    zpaList([LIVE]),
    zpaError(400, 'provisioning key name already in use'),
  ])
  try {
    const result = await deploy(deployContext([KEY]))

    assert.equal(result.success, false)
    assert.match(String(result.message), /provisioning key name already in use/)
    const rollback = result.rollbackData as { previousState: Array<{ prior?: { maxUsage?: number } }> }
    assert.equal(
      rollback.previousState[0].prior?.maxUsage,
      99,
      'the prior scalars read before the overwrite must survive the failure path',
    )
    assert.equal(leaksProvisioningKey(result), false)
    assert.equal(leaksSecret(result), false)
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: a failed component group listing stops the deploy before it writes', async () => {
  const { calls, restore } = routeFetch([{ url: /\/appConnectorGroup/, respond: serverError() }])
  try {
    const result = await deploy(deployContext([KEY]))

    assert.equal(result.success, false)
    assert.match(String(result.message), /Failed to list component groups/)
    assert.equal(resourceWrites(calls).length, 0, 'an unreadable tenant must not be written to')
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: enrollment certs unreadable on BOTH versions stops the deploy', async () => {
  // A 500 on v2 falls through to v1; if v1 cannot answer either, the certificate
  // set is unknown and resolving it to "not found" would be a guess.
  const { calls, restore } = routeFetch([
    { url: /\/enrollmentCert/, respond: serverError() },
    { url: /\/appConnectorGroup/, respond: COMPONENT_GROUPS },
  ])
  try {
    const result = await deploy(deployContext([KEY]))

    assert.equal(result.success, false)
    assert.match(String(result.message), /Failed to list enrollment certificates/)
    assert.equal(resourceWrites(calls).length, 0)
  } finally {
    restore()
  }
})

test('zpa-provisioning-keys deploy: a failed key listing stops the deploy before it writes anything', async () => {
  const { calls, restore } = routeFetch([
    { url: /\/enrollmentCert/, respond: ENROLLMENT_CERTS },
    { url: /\/appConnectorGroup/, respond: COMPONENT_GROUPS },
    { url: /\/provisioningKey/, respond: serverError() },
  ])
  try {
    const result = await deploy(deployContext([KEY]))

    assert.equal(result.success, false)
    assert.match(String(result.message), /Failed to list provisioning keys for CONNECTOR_GRP/)
    assert.equal(resourceWrites(calls).length, 0)
  } finally {
    restore()
  }
})
