import type { DeployContext, DeployResult } from '@veltrixsecops/app-sdk'
import {
  acsErrorMessage,
  acsRequest,
  parseJson,
  pollUntilReady,
  readAcsSettings,
  resolveAcsToken,
  resolveStackName,
  type AcsRequestOptions,
} from '../../lib/acs'
import {
  extractHecTokenSpecs,
  parseHecEntity,
  type HecTokenSpec,
  type LiveHecSpec,
} from './validate'

const HEC_PATH = '/inputs/http-event-collectors'

export interface HecRollbackEntry {
  name: string
  existed: boolean
  prior?: Partial<
    Pick<
      LiveHecSpec,
      'defaultIndex' | 'allowedIndexes' | 'defaultSource' | 'defaultSourcetype' | 'useAck' | 'disabled'
    >
  >
}

/**
 * Deploy HEC token configurations to a Splunk Cloud stack via the ACS API.
 *
 * For each declared token:
 *   - GET   /inputs/http-event-collectors/{name} — capture prior spec for rollback
 *   - PATCH /inputs/http-event-collectors/{name} — update managed fields that changed
 *   - POST  /inputs/http-event-collectors        — create missing, then poll until ready
 *
 * Token *values* are generated by ACS and are never captured in artifacts or
 * rollback data — retrieve them from Splunk Web or a direct ACS GET.
 */
export default async function deploy(ctx: DeployContext): Promise<DeployResult> {
  const token = resolveAcsToken(ctx.credential)
  if (!token) {
    return {
      success: false,
      message:
        'No ACS token available — store the Splunk Cloud JWT (sc_admin) in the credential "API token" field',
    }
  }

  const settings = readAcsSettings(ctx.settings)
  const stack = resolveStackName(ctx.component.hostname)
  const acs: AcsRequestOptions = {
    baseUrl: settings.baseUrl,
    stack,
    token,
    timeoutMs: settings.timeoutMs,
  }

  const specs = extractHecTokenSpecs(ctx.canvas).filter((s) => s.name)
  const rollbackState: HecRollbackEntry[] = []
  const deployed: string[] = []
  const pending: string[] = []

  try {
    for (const spec of specs) {
      const encoded = encodeURIComponent(spec.name)
      const current = await acsRequest(acs, 'GET', `${HEC_PATH}/${encoded}`)

      if (current.status === 200) {
        const live = parseHecEntity(parseJson(current.body))?.spec ?? {}

        rollbackState.push({
          name: spec.name,
          existed: true,
          prior: {
            defaultIndex: live.defaultIndex,
            allowedIndexes: live.allowedIndexes,
            defaultSource: live.defaultSource,
            defaultSourcetype: live.defaultSourcetype,
            useAck: live.useAck,
            disabled: live.disabled,
          },
        })

        const patch = buildPatch(spec, live)
        if (Object.keys(patch).length > 0) {
          const res = await acsRequest(acs, 'PATCH', `${HEC_PATH}/${encoded}`, patch)
          if (res.status !== 200 && res.status !== 202) {
            throw new Error(`Failed to update HEC token "${spec.name}": ${acsErrorMessage(res)}`)
          }
        }
      } else if (current.status === 404) {
        const res = await acsRequest(acs, 'POST', HEC_PATH, buildCreatePayload(spec))
        if (res.status !== 200 && res.status !== 201 && res.status !== 202) {
          throw new Error(`Failed to create HEC token "${spec.name}": ${acsErrorMessage(res)}`)
        }
        rollbackState.push({ name: spec.name, existed: false })

        // HEC token creation is asynchronous — poll until GET answers 200.
        const ready = await pollUntilReady(acs, `${HEC_PATH}/${encoded}`)
        if (ready === null) {
          pending.push(spec.name)
        } else if (ready.status !== 200) {
          throw new Error(`HEC token "${spec.name}" failed to provision: ${acsErrorMessage(ready)}`)
        }
      } else {
        throw new Error(`Failed to read HEC token "${spec.name}": ${acsErrorMessage(current)}`)
      }

      deployed.push(spec.name)
    }

    const pendingNote =
      pending.length > 0
        ? ` (${pending.length} still provisioning: ${pending.join(', ')})`
        : ''
    return {
      success: true,
      message: `Deployed ${deployed.length} HEC token(s) to stack "${stack}": ${deployed.join(', ')}${pendingNote}`,
      artifacts: {
        stack,
        experience: settings.experience,
        deployedTokens: deployed,
        pendingTokens: pending,
      },
      rollbackData: { previousState: rollbackState },
    }
  } catch (error) {
    return {
      success: false,
      message: `HEC token deployment to stack "${stack}" failed after ${deployed.length} of ${specs.length} token(s): ${
        error instanceof Error ? error.message : 'Unknown error'
      }`,
      artifacts: { stack, deployedTokens: deployed },
      rollbackData: { previousState: rollbackState },
    }
  }
}

// --- Helpers ---

function buildCreatePayload(spec: HecTokenSpec): Record<string, unknown> {
  const payload: Record<string, unknown> = { name: spec.name }
  if (spec.defaultIndex) payload.defaultIndex = spec.defaultIndex
  if (spec.allowedIndexes.length > 0) payload.allowedIndexes = spec.allowedIndexes
  if (spec.defaultSource) payload.defaultSource = spec.defaultSource
  if (spec.defaultSourcetype) payload.defaultSourcetype = spec.defaultSourcetype
  if (spec.useAck !== undefined) payload.useAck = spec.useAck
  if (spec.disabled !== undefined) payload.disabled = spec.disabled
  return payload
}

function sameIndexSet(a: string[] | undefined, b: string[]): boolean {
  const left = [...(a ?? [])].sort().join(',')
  const right = [...b].sort().join(',')
  return left === right
}

function buildPatch(spec: HecTokenSpec, live: LiveHecSpec): Record<string, unknown> {
  const patch: Record<string, unknown> = {}
  if (spec.defaultIndex !== undefined && spec.defaultIndex !== live.defaultIndex) {
    patch.defaultIndex = spec.defaultIndex
  }
  if (spec.allowedIndexes.length > 0 && !sameIndexSet(live.allowedIndexes, spec.allowedIndexes)) {
    patch.allowedIndexes = spec.allowedIndexes
  }
  if (spec.defaultSource !== undefined && spec.defaultSource !== live.defaultSource) {
    patch.defaultSource = spec.defaultSource
  }
  if (spec.defaultSourcetype !== undefined && spec.defaultSourcetype !== live.defaultSourcetype) {
    patch.defaultSourcetype = spec.defaultSourcetype
  }
  if (spec.useAck !== undefined && spec.useAck !== live.useAck) {
    patch.useAck = spec.useAck
  }
  if (spec.disabled !== undefined && spec.disabled !== live.disabled) {
    patch.disabled = spec.disabled
  }
  return patch
}
