import type { DeployContext, DeployResult } from '@veltrixsecops/app-sdk'
import { buildSplunkUrl, buildAuthHeader, getJson, postForm, splunkRequest, toFormBody } from '../../lib/splunkApi'

/**
 * Deploy API access token (Token Authentication) configuration via REST.
 *   enable feature: POST   /services/admin/token-auth/tokens_auth   (disabled=false)
 *   list for user:  GET    /services/authorization/tokens?username=<user>
 *   create:         POST   /services/authorization/tokens             (name=<user>, audience, type, expires_on, not_before)
 *   status update:  POST   /services/authorization/tokens/<user>      (id=<id>, status=enabled|disabled)
 *   delete:         DELETE /services/authorization/tokens/<user>      (id=<id>)
 *
 * Canvas → Splunk REST parameter mapping:
 *   username    → name (on create) / the path segment for status+delete
 *   audience    → audience
 *   tokenType   → type
 *   expiresOn   → expires_on
 *   notBefore   → not_before
 *   enabled     → status (enabled/disabled, set AFTER creation)
 *
 * A Splunk token is IMMUTABLE once created — audience, type, expires_on and
 * not_before can never be edited, only its enabled/disabled status can (see
 * "Manage or delete authentication tokens"). Splunk gives a token no name of
 * its own either, so (username, audience) is this canvas's identity for a
 * token; the platform's own token id (returned by Splunk) disambiguates when
 * more than one token shares that pair on the live instance. When an
 * immutable field drifts from what's declared, the deploy DELETES the old
 * token and CREATES a fresh one (a new token value) rather than silently
 * leaving the old one in place.
 *
 * The token VALUE is generated by Splunk and shown exactly once, at creation
 * — it is surfaced as a deploy `resources` entry (masked, reveal-once) the
 * same way hec-tokens surfaces its generated secret. A reconciled token that
 * already existed (no immutable-field change) has no value to show again.
 *
 * Source: Splunk docs — Create authentication tokens / Manage or delete
 * authentication tokens / Enable or disable token authentication
 * https://help.splunk.com/en/splunk-enterprise/administer/manage-users-and-security/10.4/authenticate-into-the-splunk-platform-with-tokens/create-authentication-tokens
 * https://help.splunk.com/en/splunk-enterprise/administer/manage-users-and-security/10.4/authenticate-into-the-splunk-platform-with-tokens/manage-or-delete-authentication-tokens
 * https://help.splunk.com/en/splunk-enterprise/administer/manage-users-and-security/10.4/authenticate-into-the-splunk-platform-with-tokens/enable-or-disable-token-authentication
 */

export const AUTH_TOKENS_PATH = '/services/authorization/tokens'
export const TOKEN_AUTH_ENABLE_PATH = '/services/admin/token-auth/tokens_auth'

/** Fields that Splunk will never let us edit on an existing token. */
const IMMUTABLE_KEYS = ['type', 'expires_on', 'not_before'] as const

interface TokenEntry {
  id?: string
  audience?: string
  type?: string
  expires_on?: string
  not_before?: string
  status?: string
  token?: string
}

/** A field the View modal renders (with copy / secret-masking). */
interface ResourceField {
  label: string
  value: string
  secret?: boolean
  copyable?: boolean
}
/** One deployed resource surfaced read-only in the config View modal. */
interface DeployedResource {
  name: string
  fields: ResourceField[]
}

interface RollbackEntry {
  username: string
  id: string
  /** Whether this deploy created the token (rollback deletes it) vs found it pre-existing (rollback restores its status). */
  created: boolean
  /** Prior status, when this deploy only reconciled status on a pre-existing token. */
  previousStatus?: string
}

export default async function deploy(ctx: DeployContext): Promise<DeployResult> {
  const { component, credential, connectivity, connectivityProvider, canvas } = ctx

  if (!credential) {
    return { success: false, message: 'Missing credential for API access token deployment' }
  }
  if (!connectivity && !connectivityProvider) {
    return { success: false, message: 'Missing connectivity for API access token deployment' }
  }

  const baseUrl = buildSplunkUrl(component, connectivity, connectivityProvider)
  const auth = buildAuthHeader(credential)

  // Idempotent, best-effort: token creation 400s while the feature is
  // disabled (its default state), mirroring the HEC "enable the global
  // input before creating tokens" precedent.
  let tokenAuthEnabled = true
  try {
    await postForm(baseUrl, auth, TOKEN_AUTH_ENABLE_PATH, { disabled: 'false' })
  } catch {
    tokenAuthEnabled = false
  }

  const rollbackEntries: RollbackEntry[] = []
  const deployedTokens: string[] = []
  const resources: DeployedResource[] = []

  try {
    for (const section of canvas.sections) {
      const fields = section.fields
      const username = fields.username as string
      const audience = fields.audience as string
      if (!username || !audience) continue

      const desiredType = typeof fields.tokenType === 'string' && fields.tokenType ? fields.tokenType : 'static'
      const desiredExpiresOn = typeof fields.expiresOn === 'string' && fields.expiresOn ? fields.expiresOn : undefined
      const desiredNotBefore = typeof fields.notBefore === 'string' && fields.notBefore ? fields.notBefore : undefined
      const desiredEnabled = fields.enabled !== false

      const existing = await findToken(baseUrl, auth, username, audience)

      let matched = existing
      if (existing) {
        const immutableDrifted = IMMUTABLE_KEYS.some((key) => {
          const desired = key === 'type' ? desiredType : key === 'expires_on' ? desiredExpiresOn : desiredNotBefore
          const live = existing[key]
          return (desired ?? '') !== (live ?? '')
        })
        if (immutableDrifted) {
          if (existing.id) {
            await deleteToken(baseUrl, auth, username, existing.id)
          }
          matched = null
        }
      }

      if (!matched) {
        const created = await createToken(baseUrl, auth, username, audience, desiredType, desiredExpiresOn, desiredNotBefore)
        if (!desiredEnabled && created.id) {
          await setTokenStatus(baseUrl, auth, username, created.id, 'disabled')
        }
        rollbackEntries.push({ username, id: created.id ?? '', created: true })
        resources.push(
          buildTokenResource(username, audience, component.hostname, {
            token: created.token,
            id: created.id,
            type: desiredType,
            expiresOn: desiredExpiresOn,
            notBefore: desiredNotBefore,
            status: desiredEnabled ? 'enabled' : 'disabled',
            freshlyCreated: true,
          }),
        )
      } else {
        const liveEnabled = String(matched.status ?? 'enabled').toLowerCase() !== 'disabled'
        if (liveEnabled !== desiredEnabled && matched.id) {
          await setTokenStatus(baseUrl, auth, username, matched.id, desiredEnabled ? 'enabled' : 'disabled')
        }
        rollbackEntries.push({ username, id: matched.id ?? '', created: false, previousStatus: matched.status })
        resources.push(
          buildTokenResource(username, audience, component.hostname, {
            id: matched.id,
            type: matched.type ?? desiredType,
            expiresOn: matched.expires_on ?? desiredExpiresOn,
            notBefore: matched.not_before ?? desiredNotBefore,
            status: desiredEnabled ? 'enabled' : 'disabled',
            freshlyCreated: false,
          }),
        )
      }

      deployedTokens.push(`${username} (${audience})`)
    }

    const authWarning = tokenAuthEnabled
      ? ''
      : ` — WARNING: could not enable Token Authentication on ${component.hostname}; tokens will not authenticate until it is enabled there`
    return {
      success: true,
      message: `Deployed ${deployedTokens.length} API access token(s): ${deployedTokens.join(', ')}${authWarning}`,
      artifacts: { deployedTokens, tokenAuthEnabled, resources },
      rollbackData: { entries: rollbackEntries },
    }
  } catch (error) {
    return {
      success: false,
      message: `API access token deployment failed after ${deployedTokens.length} token(s): ${error instanceof Error ? error.message : 'Unknown error'}`,
      artifacts: { deployedTokens },
      rollbackData: { entries: rollbackEntries },
    }
  }
}

/** Find a live token belonging to `username` whose audience matches, or null. Best-effort per-field mapping. */
async function findToken(baseUrl: string, auth: Record<string, string>, username: string, audience: string): Promise<TokenEntry | null> {
  try {
    const data = await getJson<{ entry?: Array<{ content?: TokenEntry }> }>(
      baseUrl,
      auth,
      `${AUTH_TOKENS_PATH}?username=${encodeURIComponent(username)}&count=0`,
    )
    const entries = (data.entry ?? []).map((e) => e.content).filter((c): c is TokenEntry => Boolean(c))
    return entries.find((c) => c.audience === audience) ?? null
  } catch {
    return null
  }
}

async function createToken(
  baseUrl: string,
  auth: Record<string, string>,
  username: string,
  audience: string,
  type: string,
  expiresOn: string | undefined,
  notBefore: string | undefined,
): Promise<TokenEntry> {
  const body = await postForm(baseUrl, auth, AUTH_TOKENS_PATH, {
    name: username,
    audience,
    type,
    expires_on: expiresOn,
    not_before: notBefore,
  })
  try {
    const data = JSON.parse(body) as { entry?: Array<{ content?: TokenEntry }> }
    return data.entry?.[0]?.content ?? {}
  } catch {
    return {}
  }
}

async function setTokenStatus(baseUrl: string, auth: Record<string, string>, username: string, id: string, status: 'enabled' | 'disabled'): Promise<void> {
  await postForm(baseUrl, auth, `${AUTH_TOKENS_PATH}/${encodeURIComponent(username)}`, { id, status })
}

/** DELETE sends `id` as a form-encoded body, matching the docs' `-d id=<token_id>` curl example. */
async function deleteToken(baseUrl: string, auth: Record<string, string>, username: string, id: string): Promise<void> {
  await splunkRequest(`${baseUrl}${AUTH_TOKENS_PATH}/${encodeURIComponent(username)}`, {
    method: 'DELETE',
    headers: { ...auth, 'Content-Type': 'application/x-www-form-urlencoded' },
    body: toFormBody({ id }),
  })
}

function buildTokenResource(
  username: string,
  audience: string,
  hostname: string,
  info: {
    token?: string
    id?: string
    type?: string
    expiresOn?: string
    notBefore?: string
    status: string
    freshlyCreated: boolean
  },
): DeployedResource {
  const s = (v: unknown): string => (v === undefined || v === null || v === '' ? '—' : String(v))
  return {
    name: `${username} · ${audience} · ${hostname}`,
    fields: [
      {
        label: 'Token',
        value: info.freshlyCreated ? (info.token ?? '(unavailable)') : 'Unchanged — Splunk reveals a token value only once, at creation',
        secret: info.freshlyCreated,
        copyable: info.freshlyCreated,
      },
      { label: 'Username', value: username, copyable: true },
      { label: 'Audience', value: audience },
      { label: 'Server', value: hostname },
      { label: 'Type', value: s(info.type) },
      { label: 'Expires On', value: s(info.expiresOn) },
      { label: 'Not Valid Before', value: s(info.notBefore) },
      { label: 'Status', value: info.status },
    ],
  }
}
