import type { ConfigFixture } from '../../../lib/__tests__/configFixture'

/** Blocklisted-certificate blocking is OFF on the live profile. */
export const fixture: ConfigFixture = {
  id: 'ssl-ssh-profiles',
  objectPath: '/obj/firewall/ssl-ssh-profile',
  checkName: 'fmg-ssl-ssh-profile',
  name: 'deep-inspection-corp',
  item: {
    id: 'item-1',
    name: 'deep-inspection-corp',
    fields: {
      name: 'deep-inspection-corp',
      comment: 'Corporate deep inspection',
      allowlist: true,
      blockBlocklistedCertificates: true,
      sslAnomaliesLog: true,
      sslExemptionsLog: true,
      useSslServer: false,
      serverCertMode: 're-sign',
      untrustedCaname: 'Fortinet_CA_Untrusted',
      bodyJson: '',
    },
  },
  body: {
    name: 'deep-inspection-corp',
    allowlist: 'enable',
    'block-blocklisted-certificates': 'enable',
    'ssl-anomalies-log': 'enable',
    'ssl-exemptions-log': 'enable',
    'use-ssl-server': 'disable',
    'server-cert-mode': 're-sign',
    comment: 'Corporate deep inspection',
    'untrusted-caname': 'Fortinet_CA_Untrusted',
  },
  livePrior: {
    name: 'deep-inspection-corp',
    comment: 'Corporate deep inspection',
    allowlist: 'enable',
    'block-blocklisted-certificates': 'disable',
    'ssl-anomalies-log': 'enable',
    'ssl-exemptions-log': 'enable',
    'use-ssl-server': 'disable',
    'server-cert-mode': 're-sign',
    'untrusted-caname': 'Fortinet_CA_Untrusted',
  },
  priorSnapshot: {
    name: 'deep-inspection-corp',
    comment: 'Corporate deep inspection',
    allowlist: 'enable',
    'block-blocklisted-certificates': 'disable',
    'ssl-anomalies-log': 'enable',
    'ssl-exemptions-log': 'enable',
    'use-ssl-server': 'disable',
    'server-cert-mode': 're-sign',
    'untrusted-caname': 'Fortinet_CA_Untrusted',
  },
  liveInSync: {
    name: 'deep-inspection-corp',
    comment: 'Corporate deep inspection',
    allowlist: 'enable',
    'block-blocklisted-certificates': 'enable',
    'ssl-anomalies-log': 'enable',
    'ssl-exemptions-log': 'enable',
    'use-ssl-server': 'disable',
    'server-cert-mode': 're-sign',
    'untrusted-caname': 'Fortinet_CA_Untrusted',
  },
  driftField: 'deep-inspection-corp.block-blocklisted-certificates',
  deploySuccess: 'Deployed 1 SSL/SSH profile(s)',
  deployFailurePrefix: 'Some SSL/SSH profiles failed',
  rollbackPrefix: 'Rolled back SSL/SSH profiles',
}
