import type { ConfigFixture } from '../../../lib/__tests__/configFixture'

/** Botnet C2 blocking is OFF on the live profile and on in the canvas. */
export const fixture: ConfigFixture = {
  id: 'dnsfilter-profiles',
  objectPath: '/obj/dnsfilter/profile',
  checkName: 'fmg-dnsfilter-profile',
  name: 'corp-dnsfilter',
  item: {
    id: 'item-1',
    name: 'corp-dnsfilter',
    fields: {
      name: 'corp-dnsfilter',
      comment: 'Corporate DNS filter',
      blockAction: 'block',
      blockBotnet: true,
      logAllDomain: true,
      safeSearch: false,
      redirectPortal: '10.0.0.53',
      sdnsFtgdErrLog: true,
      sdnsDomainLog: true,
      bodyJson: '',
    },
  },
  body: {
    name: 'corp-dnsfilter',
    'block-action': 'block',
    'block-botnet': 'enable',
    'log-all-domain': 'enable',
    'safe-search': 'disable',
    'sdns-ftgd-err-log': 'enable',
    'sdns-domain-log': 'enable',
    comment: 'Corporate DNS filter',
    'redirect-portal': '10.0.0.53',
  },
  livePrior: {
    name: 'corp-dnsfilter',
    comment: 'Corporate DNS filter',
    'block-action': 'block',
    'block-botnet': 'disable',
    'log-all-domain': 'enable',
    'safe-search': 'disable',
    'redirect-portal': '10.0.0.53',
    'sdns-ftgd-err-log': 'enable',
    'sdns-domain-log': 'enable',
  },
  priorSnapshot: {
    name: 'corp-dnsfilter',
    comment: 'Corporate DNS filter',
    'block-action': 'block',
    'block-botnet': 'disable',
    'log-all-domain': 'enable',
    'safe-search': 'disable',
    'redirect-portal': '10.0.0.53',
    'sdns-ftgd-err-log': 'enable',
    'sdns-domain-log': 'enable',
  },
  liveInSync: {
    name: 'corp-dnsfilter',
    comment: 'Corporate DNS filter',
    'block-action': 'block',
    'block-botnet': 'enable',
    'log-all-domain': 'enable',
    'safe-search': 'disable',
    'redirect-portal': '10.0.0.53',
    'sdns-ftgd-err-log': 'enable',
    'sdns-domain-log': 'enable',
  },
  driftField: 'corp-dnsfilter.block-botnet',
  deploySuccess: 'Deployed 1 DNS filter profile(s)',
  deployFailurePrefix: 'Some DNS filter profiles failed',
  rollbackPrefix: 'Rolled back DNS filter profiles',
}
