// Shared helpers for the SonarQube Global Settings config type (validate + deploy +
// rollback + drift). Pure and network-free so validate.ts and the tests can use it.
//
// A global setting is authored as a `sonar.*` key and either a single scalar value or a
// multi-value list (one value per line) — GLOBAL scope only, `component` is never sent;
// per-project settings are a separate, project-scoped surface this config type does not
// touch. PROPERTY_SET settings (a `fieldValues` array of per-occurrence sub-objects, e.g.
// SonarQube's own `sonar.demo` example below) are OUT OF SCOPE: their field schema is
// per-setting and unpredictable, so this type never reads or writes `fieldValues` at all —
// author those, if ever needed, directly in SonarQube.
//
// Verified live against a running SonarQube instance's own `api/webservices` reflection
// endpoints (api/webservices/list?include_internals=true, api/webservices/response_example).
// Example api/settings/values response:
//   { "settings": [
//       { "key": "sonar.test.jira", "value": "abc", "inherited": true },
//       { "key": "sonar.autogenerated", "values": ["val1","val2","val3"], "inherited": false },
//       { "key": "sonar.demo", "fieldValues": [{"boolean":"true","text":"foo"}], "inherited": false }
//     ],
//     "setSecuredSettings": ["email.smtp_port.secured"] }
// `inherited: true` means the setting is currently at its default (nothing explicitly set
// at this level) — treated as "not currently declared" for drift/rollback purposes.

/** A setting as returned by /api/settings/values ({ key, value | values | fieldValues, inherited }). */
export interface SonarSetting {
  key?: string
  value?: string
  values?: string[]
  fieldValues?: unknown[]
  inherited?: boolean
}

/**
 * Parse the values textarea: one value per line, trimmed; blank lines and lines starting
 * with `#` are ignored.
 */
export function parseValueLines(text: unknown): string[] {
  return String(text ?? '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line !== '' && !line.startsWith('#'))
}

/** Unwrap SonarQube's `{ settings: [...] }` envelope into a flat array. */
export function settingsFromValues(payload: unknown): SonarSetting[] {
  if (payload && typeof payload === 'object' && Array.isArray((payload as { settings?: unknown }).settings)) {
    return (payload as { settings: SonarSetting[] }).settings
  }
  return []
}

/** Find a live setting by exact key. */
export function findSetting(settings: SonarSetting[], key: string): SonarSetting | null {
  const k = key.trim()
  return settings.find((s) => String(s.key ?? '').trim() === k) ?? null
}
