// =============================================================================
// SailPoint Identity Security Cloud (ISC) API client.
//
// Auth is OAuth2 client-credentials against an ISC tenant:
//   POST https://{tenant}.api.identitynow.com/oauth/token
//   grant_type=client_credentials, client_id, client_secret  (no scope param)
// The returned bearer token is cached until ~1 min before expiry.
//
// Convention for the Veltrix credential:
//   username -> ISC client id  (a PAT's Client ID, or an OAuth client id)
//   password -> ISC client secret
//   tenant   -> the `tenant` app setting (the org name, e.g. "acme"), or a full
//               `api_url` override for non-standard API hosts.
//
// Data routes use the new per-service scheme, e.g. /transforms/v1. ISC list
// endpoints return a BARE JSON array and paginate with offset/limit (max 250);
// `count=true` populates the X-Total-Count header. Rate limiting is 429 +
// `Retry-After` (seconds). Handlers run in-process in the platform's Node
// runtime, so this uses fetch with an AbortController timeout and no external
// HTTP dependency. It never throws on an HTTP error status — callers inspect
// `status` so a 404 (object absent) is distinguishable from a real failure.
// =============================================================================

import type { CredentialRef } from '@veltrixsecops/app-sdk'

const REQUEST_TIMEOUT_MS = 30_000
const MAX_RATE_LIMIT_WAIT_MS = 20_000
/** ISC list endpoints cap `limit` at 250. */
export const MAX_PAGE_LIMIT = 250
/** Refresh the token this many ms before its stated expiry. */
const TOKEN_SKEW_MS = 60_000

export interface IscSettings {
  timeoutMs: number
  /** Fully-resolved API base, e.g. https://acme.api.identitynow.com (no trailing slash). */
  baseUrl: string | null
}

/** Build the ISC API base URL from the org name, or accept a full override. */
export function resolveBaseUrl(settings: Record<string, unknown>): string | null {
  const rawApiUrl = settings.api_url
  if (typeof rawApiUrl === 'string' && rawApiUrl.trim()) {
    return rawApiUrl.trim().replace(/\/+$/, '')
  }
  const rawTenant = settings.tenant
  if (typeof rawTenant === 'string' && rawTenant.trim()) {
    const org = rawTenant.trim().replace(/^https?:\/\//, '').replace(/\..*$/, '')
    if (org) return `https://${org}.api.identitynow.com`
  }
  return null
}

export function readIscSettings(settings: Record<string, unknown>): IscSettings {
  const rawTimeout = settings.request_timeout_seconds
  const timeoutMs =
    typeof rawTimeout === 'number' && Number.isFinite(rawTimeout) && rawTimeout > 0
      ? rawTimeout * 1000
      : REQUEST_TIMEOUT_MS
  return { timeoutMs, baseUrl: resolveBaseUrl(settings) }
}

export interface IscCredential {
  baseUrl: string
  clientId: string
  clientSecret: string
}

/**
 * Resolve the ISC OAuth client credential. Returns null if any of the three
 * required parts is missing so callers can surface MISSING_CREDENTIAL_MESSAGE.
 */
export function resolveIscCredential(
  credential: CredentialRef | null,
  settings: IscSettings
): IscCredential | null {
  if (!credential) return null
  const clientId = (credential.username ?? '').trim()
  const clientSecret = (credential.password ?? '').trim()
  const baseUrl = (settings.baseUrl ?? '').trim()
  if (!clientId || !clientSecret || !baseUrl) return null
  return { baseUrl, clientId, clientSecret }
}

export const MISSING_CREDENTIAL_MESSAGE =
  'No usable SailPoint ISC credential — this app authenticates to Identity Security Cloud via ' +
  'OAuth2 client credentials. Store the Client ID in the credential "username" field and the ' +
  'Client Secret in "password" (a Personal Access Token generated by an ORG_ADMIN user works), and ' +
  'set the tenant (org name, e.g. "acme") in the app\'s "Tenant" setting. The client needs the ' +
  'relevant :manage / :read scopes for what this app manages.'

export interface IscResponse {
  status: number
  ok: boolean
  body: string
  /** X-Total-Count when requested with count=true. */
  totalCount: number | null
}

export type IscMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms))

export class IscClient {
  private readonly cred: IscCredential
  private readonly timeoutMs: number
  private token: string | null = null
  private tokenExpiresAt = 0

  constructor(opts: { cred: IscCredential; timeoutMs: number }) {
    this.cred = opts.cred
    this.timeoutMs = opts.timeoutMs
  }

  /** Acquire (and cache) a bearer token. Returns an error string on failure. */
  private async ensureToken(): Promise<{ token?: string; error?: string }> {
    if (this.token && Date.now() < this.tokenExpiresAt - TOKEN_SKEW_MS) {
      return { token: this.token }
    }
    const url = `${this.cred.baseUrl}/oauth/token`
    const form = new URLSearchParams({
      grant_type: 'client_credentials',
      client_id: this.cred.clientId,
      client_secret: this.cred.clientSecret,
    })
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), this.timeoutMs)
    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: form.toString(),
        signal: controller.signal,
      })
      const body = await res.text()
      if (!res.ok) {
        const parsed = parseJson<{ error_description?: string; error?: string }>(body)
        return { error: parsed?.error_description || parsed?.error || `token request failed (${res.status})` }
      }
      const parsed = parseJson<{ access_token?: string; expires_in?: number }>(body)
      if (!parsed?.access_token) return { error: 'token response missing access_token' }
      this.token = parsed.access_token
      this.tokenExpiresAt = Date.now() + (parsed.expires_in ?? 43200) * 1000
      return { token: this.token }
    } catch (err) {
      return { error: err instanceof Error ? err.message : 'token request error' }
    } finally {
      clearTimeout(timer)
    }
  }

  /** Make an ISC request. `path` is either an absolute URL or a base-relative
   *  path like `/transforms/v1`. `contentType` overrides the request body type
   *  (e.g. `application/json-patch+json` for JSON-Patch endpoints). */
  async request(
    method: IscMethod,
    path: string,
    body?: unknown,
    opts?: { contentType?: string }
  ): Promise<IscResponse> {
    const auth = await this.ensureToken()
    if (auth.error || !auth.token) {
      return { status: 0, ok: false, body: auth.error ?? 'no token', totalCount: null }
    }
    const url = path.startsWith('http') ? path : `${this.cred.baseUrl}${path.startsWith('/') ? path : `/${path}`}`

    for (let attempt = 0; attempt < 2; attempt++) {
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(), this.timeoutMs)
      try {
        const res = await fetch(url, {
          method,
          headers: {
            Authorization: `Bearer ${auth.token}`,
            'Content-Type': opts?.contentType ?? 'application/json',
            Accept: 'application/json',
          },
          body: body === undefined ? undefined : JSON.stringify(body),
          signal: controller.signal,
        })
        const text = await res.text()

        // Retry once on 429, honoring Retry-After (seconds), capped.
        if (res.status === 429 && attempt === 0) {
          const retryAfter = Number(res.headers.get('Retry-After'))
          const waitMs = Number.isFinite(retryAfter) && retryAfter > 0
            ? Math.min(retryAfter * 1000, MAX_RATE_LIMIT_WAIT_MS)
            : 1000
          await sleep(waitMs)
          continue
        }

        const totalHeader = res.headers.get('X-Total-Count')
        const totalCount = totalHeader !== null && Number.isFinite(Number(totalHeader)) ? Number(totalHeader) : null
        return { status: res.status, ok: res.ok, body: text, totalCount }
      } catch (err) {
        if (attempt === 0) continue
        return {
          status: 0,
          ok: false,
          body: err instanceof Error ? err.message : 'request error',
          totalCount: null,
        }
      } finally {
        clearTimeout(timer)
      }
    }
    return { status: 0, ok: false, body: 'request failed', totalCount: null }
  }

  get(path: string): Promise<IscResponse> {
    return this.request('GET', path)
  }
  post(path: string, body: unknown): Promise<IscResponse> {
    return this.request('POST', path, body)
  }
  put(path: string, body: unknown): Promise<IscResponse> {
    return this.request('PUT', path, body)
  }
  patch(path: string, body: unknown, contentType = 'application/json-patch+json'): Promise<IscResponse> {
    return this.request('PATCH', path, body, { contentType })
  }
  delete(path: string): Promise<IscResponse> {
    return this.request('DELETE', path)
  }

  /** GET a collection following offset/limit pagination (bare-array pages). */
  async getAll<T = unknown>(
    path: string,
    pageLimit = MAX_PAGE_LIMIT,
    maxPages = 40
  ): Promise<{ ok: boolean; items: T[]; lastError?: IscResponse }> {
    const limit = Math.min(Math.max(pageLimit, 1), MAX_PAGE_LIMIT)
    const items: T[] = []
    for (let page = 0; page < maxPages; page++) {
      const offset = page * limit
      const sep = path.includes('?') ? '&' : '?'
      const res = await this.get(`${path}${sep}offset=${offset}&limit=${limit}`)
      if (!res.ok) return { ok: false, items, lastError: res }
      const arr = parseJson<T[]>(res.body)
      if (!Array.isArray(arr) || arr.length === 0) break
      items.push(...arr)
      if (arr.length < limit) break
    }
    return { ok: true, items }
  }
}

export function buildIscClient(cred: IscCredential, settings: IscSettings): IscClient {
  return new IscClient({ cred, timeoutMs: settings.timeoutMs })
}

export function parseJson<T>(body: string): T | null {
  try {
    return JSON.parse(body) as T
  } catch {
    return null
  }
}

/** Extract a human-readable message from an ISC error response body. */
export function iscErrorMessage(resp: IscResponse): string {
  const parsed = parseJson<{
    detailCode?: string
    messages?: Array<{ text?: string }>
    message?: string
    error?: string
  }>(resp.body)
  if (parsed) {
    const detail = parsed.messages?.map((m) => m.text).filter(Boolean).join('; ')
    const msg = detail || parsed.message || parsed.error
    if (msg) return parsed.detailCode ? `${parsed.detailCode}: ${msg}` : msg
  }
  return resp.body?.slice(0, 300) || `ISC request failed (status ${resp.status})`
}
